'use strict';
/**
 * tools/games/_extract.js  (dev-time helper)
 *
 * Slices the proven shared fragments out of the reference implementation
 * games/memory-match.html and writes them to tools/games/_shared.js as
 * template strings.  Run once; the output is the single source of truth for
 * the shared shell every Kids Learning game reuses.
 *
 * The generated games/*.html files remain fully standalone — this is an
 * authoring aid, exactly like tools/build-katha.js is for content/.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
const REF = path.join(ROOT, 'games', 'memory-match.html');
const OUT = path.join(__dirname, '_shared.js');

const html = fs.readFileSync(REF, 'utf8');

function between(startMark, endMark, label) {
  const s = html.indexOf(startMark);
  if (s < 0) throw new Error('start marker not found: ' + label);
  const e = html.indexOf(endMark, s + startMark.length);
  if (e < 0) throw new Error('end marker not found: ' + label);
  return html.slice(s, e);
}

/* ---- CSS: the whole stylesheet, reused verbatim as the shared base ---- */
const css = between('<style>', '</style>', 'css')
  .replace(/^<style>\r?\n/, '');

/* ---- JS: DATA region (Tirthankara table + enums) ---- */
const tirth = between(
  'var SS_EN =',
  '/* ============================================================\r\n   UI DICTIONARY',
  'tirth');

/* ---- JS: CORE HELPERS + AUDIO + SVG ART (up to STATE) ---- */
const core = between(
  '/* ============================================================\r\n   CORE HELPERS',
  '/* ============================================================\r\n   STATE',
  'core');

/* ---- JS: TOAST/DIALOG/PARTICLES + LEADERBOARD (up to RENDER) ---- */
const shell = between(
  '/* ============================================================\r\n   TOAST / DIALOG / PARTICLES',
  '/* ============================================================\r\n   RENDER',
  'shell');

/* The leaderboard comparator is game-specific; expose it as a hook. */
const shellGeneric = shell.replace(
  /function lbCmp\(a, b\) \{[\s\S]*?\n\}/,
  'function lbCmp(a, b) { return LB_CMP(a, b); }');

function asTemplate(s) {
  return '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
}

const out = [
  "'use strict';",
  '/* GENERATED by tools/games/_extract.js from games/memory-match.html.',
  '   Do not edit by hand — edit the reference game and re-run the extractor. */',
  '',
  'const CSS_BASE = ' + asTemplate(css) + ';',
  '',
  'const JS_TIRTH = ' + asTemplate(tirth) + ';',
  '',
  'const JS_CORE = ' + asTemplate(core) + ';',
  '',
  'const JS_SHELL = ' + asTemplate(shellGeneric) + ';',
  '',
  'module.exports = { CSS_BASE, JS_TIRTH, JS_CORE, JS_SHELL };',
  ''
].join('\n');

fs.writeFileSync(OUT, out, 'utf8');
console.log('wrote', path.relative(ROOT, OUT), Buffer.byteLength(out, 'utf8'), 'bytes');
console.log('  CSS_BASE :', css.length, 'chars');
console.log('  JS_TIRTH :', tirth.length, 'chars');
console.log('  JS_CORE  :', core.length, 'chars');
console.log('  JS_SHELL :', shellGeneric.length, 'chars');
console.log('  lbCmp hooked:', shellGeneric.indexOf('LB_CMP(a, b)') >= 0);
