'use strict';
/* GENERATED by tools/games/_extract.js from games/memory-match.html.
   Do not edit by hand — edit the reference game and re-run the extractor. */

const CSS_BASE = `/* ============================================================
   स्मृति पट्ट · Memory Match
   Single file · no CDN · no images · no external fonts
   Motion: transform + opacity only · honours prefers-reduced-motion
   ============================================================ */
:root{
  --saffron:#E8800C; --maroon:#6D1B2F; --gold:#C8860A; --cream:#FFF8F0;
  --warm:#FFFBF5; --ink:#2D1B06; --ink2:#5C3D1E; --border:#D4A574;
  --success:#2E7D32; --rose:#B23A3A; --leaf:#3F7D4F; --info:#1565C0;
  --card-line:#EADBC0;
  --r-sm:6px; --r-md:10px; --r-lg:16px; --r-full:9999px;
  --sh-sm:0 1px 3px rgba(45,27,6,.08), 0 1px 2px rgba(45,27,6,.06);
  --sh-md:0 4px 12px rgba(45,27,6,.10), 0 2px 4px rgba(45,27,6,.06);
  --sh-lg:0 10px 25px rgba(45,27,6,.12), 0 4px 8px rgba(45,27,6,.06);
  --fast:.15s ease; --base:.25s ease; --slow:.4s ease;
  --ritual:.7s cubic-bezier(.2,.7,.2,1);
  --font-head:'Noto Serif Devanagari', Georgia, 'Times New Roman', serif;
  --font-body:'Noto Sans Devanagari', system-ui, -apple-system, 'Segoe UI', sans-serif;
}
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
html{font-size:16px;-webkit-text-size-adjust:100%}
@media (max-width:480px){html{font-size:15px}}
body{
  font-family:var(--font-body);color:var(--ink);line-height:1.6;min-height:100vh;
  background:
    radial-gradient(900px 480px at 50% -10%, #FFF6E2 0%, transparent 62%),
    linear-gradient(165deg,#FDF8EE,#F7ECD6 60%,#F1E2C4);
  -webkit-font-smoothing:antialiased;overflow-x:hidden;
  -webkit-tap-highlight-color:transparent;
}
button,input,select{font:inherit;color:inherit}
button{background:none;border:none;cursor:pointer}
img,svg{display:block;max-width:100%}
:focus-visible{outline:3px solid var(--saffron);outline-offset:2px;border-radius:var(--r-sm)}
.is-hidden{display:none!important}
.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;
  clip:rect(0 0 0 0);white-space:nowrap;border:0}

.g-wrap{max-width:900px;margin:0 auto;padding:14px 14px 40px}

/* ---------- header ---------- */
.g-head{display:flex;align-items:center;gap:10px;flex-wrap:wrap;padding:8px 2px 14px}
.g-brand{display:flex;align-items:center;gap:9px;min-width:0}
.g-mark{width:30px;height:30px;flex-shrink:0;color:var(--saffron)}
.g-brand-txt{display:flex;flex-direction:column;min-width:0}
.g-brand-hi{font-family:var(--font-head);font-weight:700;font-size:1.02rem;
  color:var(--maroon);line-height:1.2;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.g-brand-en{font-size:.68rem;letter-spacing:.08em;text-transform:uppercase;color:var(--ink2);opacity:.85}
.g-head-actions{display:flex;align-items:center;gap:6px;margin-left:auto;flex-wrap:wrap}
.g-pill{border:1.5px solid var(--border);background:rgba(255,255,255,.72);
  border-radius:var(--r-full);padding:6px 13px;font-weight:600;font-size:.76rem;
  color:#7A5A12;transition:background var(--fast),transform var(--fast);white-space:nowrap;min-height:36px}
.g-pill:hover{background:#fff;transform:translateY(-1px)}
.g-iconbtn{width:38px;height:38px;display:grid;place-items:center;border-radius:var(--r-full);
  border:1.5px solid var(--border);background:rgba(255,255,255,.72);color:var(--maroon);
  transition:background var(--fast)}
.g-iconbtn:hover{background:#fff}
.g-iconbtn svg{width:19px;height:19px}

/* ---------- screens ---------- */
.g-screen{animation:g-rise .5s cubic-bezier(.2,.7,.2,1)}
@keyframes g-rise{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none}}
.g-card{background:var(--warm);border:1px solid var(--card-line);border-radius:var(--r-lg);
  box-shadow:var(--sh-md);padding:26px 20px;margin:14px 0;text-align:center}
.g-rule{width:56px;height:2px;margin:0 auto 18px;
  background:linear-gradient(90deg,transparent,var(--gold),transparent)}
.g-title{font-family:var(--font-head);font-weight:700;color:var(--maroon);
  font-size:clamp(1.4rem,4.6vw,2rem);line-height:1.25;margin-bottom:.25em}
.g-sub{color:var(--ink2);font-size:.95rem;max-width:46ch;margin:0 auto 1.2em}
.g-glyph{display:block;width:64px;height:64px;margin:0 auto 10px;color:var(--saffron)}
.g-glyph svg{width:100%;height:100%}

/* ---------- choice tiles ---------- */
.g-choices{display:flex;gap:12px;justify-content:center;flex-wrap:wrap;margin-top:8px}
.g-choice{border:1.5px solid var(--border);background:rgba(255,255,255,.62);
  border-radius:var(--r-lg);padding:18px 20px;min-width:140px;flex:0 1 190px;
  color:var(--maroon);text-align:center;
  transition:transform var(--base),background var(--base),border-color var(--base),box-shadow var(--base)}
.g-choice:hover{transform:translateY(-3px);background:#fff;box-shadow:var(--sh-md);border-color:var(--saffron)}
.g-choice.is-on{border-color:var(--maroon);background:#fff;box-shadow:0 0 0 2px rgba(109,27,47,.16)}
.g-choice-mark{width:34px;height:34px;margin:0 auto 8px;color:var(--saffron)}
.g-choice-name{display:block;font-family:var(--font-head);font-weight:700;font-size:1.02rem}
.g-choice-note{display:block;font-size:.74rem;color:var(--ink2);margin-top:3px;opacity:.9}
@media (pointer:coarse){.g-choice{min-height:44px}}

/* ---------- setup form ---------- */
.g-field{text-align:left;margin:20px auto 0;max-width:540px}
.g-label{display:block;font-weight:700;font-size:.84rem;color:var(--maroon);margin-bottom:8px;
  letter-spacing:.02em}
.g-input{width:100%;padding:12px 14px;border:1.5px solid var(--border);border-radius:var(--r-md);
  background:#fff;font-size:1rem;min-height:46px;transition:border-color var(--fast)}
.g-input:focus{border-color:var(--saffron);outline:none}
.g-chips{display:flex;flex-wrap:wrap;gap:8px}
.g-chip{border:1.5px solid var(--border);background:rgba(255,255,255,.7);
  border-radius:var(--r-full);padding:8px 15px;font-size:.84rem;font-weight:600;color:#6B5733;
  min-height:42px;transition:background var(--fast),border-color var(--fast),color var(--fast)}
.g-chip:hover{background:#fff;border-color:var(--saffron)}
.g-chip.is-on{background:var(--maroon);border-color:var(--maroon);color:#fff}
.g-hint{font-size:.8rem;color:var(--ink2);margin-top:16px;font-style:italic}

/* ---------- buttons ---------- */
.g-btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;
  border:1.5px solid var(--border);background:rgba(255,255,255,.75);border-radius:var(--r-full);
  padding:12px 26px;font-weight:700;font-size:.95rem;color:#7A5A12;min-height:46px;
  transition:transform var(--fast),background var(--fast),box-shadow var(--fast)}
.g-btn:hover{background:#fff;transform:translateY(-2px);box-shadow:var(--sh-sm)}
.g-btn-primary{background:linear-gradient(180deg,var(--saffron),#D0710A);border-color:#B85F08;
  color:#fff;box-shadow:0 3px 0 #A85607}
.g-btn-primary:hover{background:linear-gradient(180deg,#F08C15,var(--saffron));color:#fff}
.g-btn-primary:active{transform:translateY(2px);box-shadow:0 1px 0 #A85607}
.g-btn-primary:disabled{background:#D9CDB8;border-color:#C9BCA5;box-shadow:none;color:#8B7C63;
  cursor:not-allowed;transform:none}
.g-btn-row{display:flex;gap:10px;justify-content:center;flex-wrap:wrap;margin-top:20px}
.g-btn-sm{padding:8px 16px;font-size:.82rem;min-height:38px}

/* ---------- HUD ---------- */
.g-hud{display:flex;gap:8px;align-items:center;flex-wrap:wrap;justify-content:center;
  background:rgba(255,255,255,.6);border:1px solid var(--card-line);border-radius:var(--r-lg);
  padding:10px 12px;margin:6px 0 14px}
.g-stat{display:flex;flex-direction:column;align-items:center;min-width:66px;padding:2px 8px}
.g-stat-val{font-family:var(--font-head);font-weight:700;font-size:1.15rem;color:var(--maroon);
  line-height:1.15;font-variant-numeric:tabular-nums}
.g-stat-lbl{font-size:.66rem;letter-spacing:.06em;text-transform:uppercase;color:var(--ink2);opacity:.85}
.g-hud-sep{width:1px;height:26px;background:var(--card-line)}
.g-progress{height:6px;background:rgba(212,165,116,.32);border-radius:var(--r-full);
  overflow:hidden;width:100%;margin-top:4px}
.g-progress-fill{height:100%;width:100%;border-radius:var(--r-full);transform-origin:left center;
  transform:scaleX(0);background:linear-gradient(90deg,var(--gold),var(--saffron));
  transition:transform var(--slow)}

/* ---------- memory grid ---------- */
.g-board{display:grid;gap:10px;grid-template-columns:repeat(4,1fr);margin:4px 0 8px;
  perspective:1200px}
@media (min-width:620px){.g-board[data-cols="12"]{grid-template-columns:repeat(6,1fr)}}
@media (max-width:400px){.g-board{gap:7px}}
/* tight board: cards fill cells, no aspect-ratio constraint */
.g-board.is-tight{grid-auto-rows:1fr}
.g-board.is-tight .g-cardflip{aspect-ratio:auto;height:100%;min-height:0}
.g-board.is-tight .g-face{padding:4px 3px;gap:3px}
.g-board.is-tight .g-face-back .g-art{width:28px;height:28px}
.g-board.is-tight .g-face-back .g-txt{font-size:.62rem}
.g-board.is-tight .g-face-back .g-sub2{font-size:.54rem}
.g-board.is-tight .g-face-front svg{width:44%;height:auto}

/* The flip lives on the WRAPPER only. Neither face is itself rotated, so no
   glyph can ever be painted mirrored. The hidden face also drops to
   opacity 0 after the turn, which makes a mirrored render impossible even
   where backface-visibility is unsupported. */
.g-cardflip{position:relative;aspect-ratio:3/4;cursor:pointer;
  transform-style:preserve-3d;transition:transform .55s cubic-bezier(.2,.7,.2,1)}
.g-cardflip.is-flipped{transform:rotateY(180deg)}
.g-face{position:absolute;inset:0;border-radius:var(--r-md);
  display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;
  padding:8px 6px;text-align:center;overflow:hidden;
  -webkit-backface-visibility:hidden;backface-visibility:hidden;
  transition:opacity .2s linear .35s, box-shadow var(--base)}
.g-cardflip.is-flipped .g-face-front{opacity:0}
.g-cardflip:not(.is-flipped) .g-face-back{opacity:0}
.g-face-front{background:linear-gradient(150deg,#FBEBCB,#F2DCB0);
  border:1.5px solid var(--border);box-shadow:var(--sh-sm);color:var(--gold)}
.g-face-front svg{width:64%;height:auto;color:var(--gold);opacity:.85}
.g-face-back{transform:rotateY(180deg);background:#fff;border:1.5px solid var(--card-line);
  box-shadow:var(--sh-sm);color:var(--ink)}
.g-face-back .g-art{width:44px;height:44px;flex-shrink:0}
.g-face-back .g-txt{font-size:.74rem;font-weight:700;line-height:1.3;color:var(--maroon);
  overflow-wrap:anywhere}
.g-face-back .g-sub2{font-size:.64rem;color:var(--ink2);opacity:.85;line-height:1.25}
.g-cardflip.is-matched{cursor:default}
.g-cardflip.is-matched .g-face-back{border-color:var(--gold);
  box-shadow:0 0 0 2px rgba(200,134,10,.28), var(--sh-md)}
.g-cardflip.is-matched .g-face-back .g-txt{color:var(--leaf)}
.g-cardflip.is-wrong{animation:g-sway .42s ease}
@keyframes g-sway{0%,100%{transform:rotateY(180deg) translateX(0)}
  25%{transform:rotateY(180deg) translateX(-4px)}
  75%{transform:rotateY(180deg) translateX(4px)}}
.g-cardflip.is-hint .g-face-back{box-shadow:0 0 0 3px rgba(232,128,12,.45)}
@media (max-width:400px){
  .g-face-back .g-art{width:32px;height:32px}
  .g-face-back .g-txt{font-size:.66rem}
  .g-face-back .g-sub2{font-size:.58rem}
}

/* ---------- result ---------- */
.g-medal{display:block;width:76px;height:76px;margin:0 auto 8px;color:var(--gold);
  animation:g-bloom .8s cubic-bezier(.2,.8,.25,1)}
.g-medal svg{width:100%;height:100%}
@keyframes g-bloom{from{opacity:0;transform:scale(.72)}to{opacity:1;transform:scale(1)}}
.g-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));gap:10px;margin:18px 0}
.g-statbox{background:#fff;border:1px solid var(--card-line);border-radius:var(--r-md);padding:13px 8px}
.g-statbox b{display:block;font-family:var(--font-head);font-size:1.4rem;color:var(--saffron);
  line-height:1.2;font-variant-numeric:tabular-nums}
.g-statbox span{display:block;font-size:.66rem;letter-spacing:.06em;text-transform:uppercase;
  color:var(--ink2);margin-top:3px}
.g-review{text-align:left;margin:18px auto 0;max-width:640px}
.g-review-title{font-family:var(--font-head);font-weight:700;color:var(--maroon);
  font-size:1.02rem;text-align:center;margin-bottom:10px}
.g-tablewrap{overflow-x:auto;border:1px solid var(--card-line);border-radius:var(--r-md);background:#fff}
.g-table{width:100%;border-collapse:collapse;font-size:.82rem;min-width:430px}
.g-table th,.g-table td{padding:9px 10px;text-align:left;border-bottom:1px solid #F1E6D2;vertical-align:top}
.g-table th{background:#FBF3E2;font-weight:700;color:var(--maroon);font-size:.7rem;
  letter-spacing:.05em;text-transform:uppercase;white-space:nowrap}
.g-table tbody tr:last-child td{border-bottom:none}
.g-table td.g-num{font-variant-numeric:tabular-nums;color:var(--ink2);width:2.4em}
.g-note{font-size:.8rem;color:var(--ink2);background:#FBF3E2;border-left:3px solid var(--gold);
  padding:9px 12px;border-radius:0 var(--r-sm) var(--r-sm) 0;margin-top:14px;line-height:1.55}
.g-rank{display:inline-block;background:var(--gold);color:#4A3508;border-radius:var(--r-full);
  padding:4px 14px;font-weight:700;font-size:.8rem;margin-top:12px}

/* ---------- leaderboard ---------- */
.g-lb{text-align:left;margin-top:18px}
.g-lb-head{display:flex;align-items:center;justify-content:space-between;gap:10px;
  flex-wrap:wrap;margin-bottom:10px}
.g-lb-title{font-family:var(--font-head);font-weight:700;color:var(--maroon);font-size:1.02rem}
.g-lb-empty{font-size:.84rem;color:var(--ink2);font-style:italic;text-align:center;padding:14px 6px}
.g-medalcell{font-weight:700;color:var(--gold);width:2.6em}

/* ---------- toast / dialog / fx ---------- */
.g-toast{position:fixed;left:50%;bottom:24px;z-index:70;max-width:min(92vw,430px);
  transform:translateX(-50%) translateY(120px);opacity:0;pointer-events:none;
  background:rgba(60,40,20,.94);color:#FFF6E2;padding:11px 20px;border-radius:var(--r-full);
  font-weight:600;font-size:.86rem;box-shadow:var(--sh-lg);text-align:center;line-height:1.45;
  transition:transform var(--slow),opacity var(--slow)}
.g-toast.is-on{transform:translateX(-50%) translateY(0);opacity:1}
.g-fx{position:fixed;inset:0;pointer-events:none;overflow:hidden;z-index:60}
.g-fx i{position:absolute;top:-24px;display:block;
  border-radius:60% 60% 60% 60%/70% 70% 30% 30%;
  animation:g-fall linear forwards;will-change:transform,opacity}
@keyframes g-fall{to{transform:translateY(112vh) rotate(420deg);opacity:.15}}
.g-dialog{position:fixed;inset:0;z-index:80;display:grid;place-items:center;padding:20px;
  background:rgba(45,27,6,.55)}
.g-dialog-card{background:var(--warm);border:1px solid var(--border);border-radius:var(--r-lg);
  box-shadow:var(--sh-lg);padding:26px 22px;max-width:400px;width:100%;text-align:center;
  animation:g-rise .35s cubic-bezier(.2,.7,.2,1)}
.g-dialog-card h2{font-family:var(--font-head);color:var(--maroon);font-size:1.2rem;margin-bottom:8px}
.g-dialog-card p{font-size:.9rem;color:var(--ink2);margin-bottom:6px}
.g-foot{text-align:center;color:#A08A5E;font-size:.74rem;margin:28px auto 0;line-height:1.7;
  font-style:italic;max-width:60ch}

/* ---------- reduced motion ---------- */
@media (prefers-reduced-motion: reduce){
  *,*::before,*::after{animation-duration:.001ms!important;animation-iteration-count:1!important;
    transition-duration:.001ms!important;scroll-behavior:auto!important}
  .g-fx{display:none!important}
}

/* ---------- short desktop: compact play screens so they fit the iframe without scrolling ---------- */
@media (min-width:900px) and (max-height:880px){
  .g-wrap{padding:8px 14px 20px}
  .g-card{padding:18px 16px;margin:8px 0}
  .g-title{font-size:clamp(1.2rem,3.6vw,1.6rem);margin-bottom:.15em}
  .g-sub{font-size:.85rem;margin-bottom:.8em}
  .g-hud{padding:8px 10px;margin:4px 0 8px}
  .g-stat-val{font-size:1rem}
  .g-stat-lbl{font-size:.58rem}
  .g-btn-row{margin-top:10px}
  .g-btn{padding:10px 20px;min-height:40px;font-size:.85rem}
  .g-btn-sm{padding:7px 14px;min-height:34px;font-size:.78rem}
  .g-foot{margin:14px auto 0;font-size:.68rem}
  .g-board{margin:2px 0 6px}
  .g-cardflip{aspect-ratio:auto;min-height:0}
  .g-face{padding:6px 4px;gap:4px}
  .g-face-back .g-art{width:36px;height:36px}
  .g-face-back .g-txt{font-size:.68rem}
  .g-face-front svg{width:50%;height:auto}
  .g-medal{width:56px;height:56px}
  .g-stats{margin:12px 0;gap:8px}
  .g-statbox{padding:10px 6px}
  .g-statbox b{font-size:1.2rem}
  .g-statbox span{font-size:.6rem}
  .g-review{margin:12px auto 0}
  .g-note{margin-top:10px;padding:7px 10px;font-size:.74rem}
}
`;

const JS_TIRTH = `var SS_EN = 'Sammed Shikharji', SS_HI = 'सम्मेद शिखरजी';
var G = '#E3B23C', R = '#C0392B', W = '#F2EDE4', B = '#2E5FA3', D = '#3A3A44';
var T_ROWS = [
[1,'Rishabhanatha','ऋषभनाथ','Adinatha','आदिनाथ','Bull','वृषभ','bull','Golden','स्वर्ण',G,'golden','seated','Ashtapada','अष्टापद','ashtapada','Ayodhya','अयोध्या','ayodhya'],
[2,'Ajitanatha','अजितनाथ','','','Elephant','हाथी','elephant','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Ayodhya','अयोध्या','ayodhya'],
[3,'Sambhavanatha','सम्भवनाथ','','','Horse','अश्व','horse','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Shravasti','श्रावस्ती','shravasti'],
[4,'Abhinandananatha','अभिनन्दन','','','Monkey','कपि','monkey','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Ayodhya','अयोध्या','ayodhya'],
[5,'Sumatinatha','सुमतिनाथ','','','Curlew','क्रौंच','curlew','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Ayodhya','अयोध्या','ayodhya'],
[6,'Padmaprabha','पद्मप्रभ','','','Red Lotus','लाल कमल','lotusRed','Red','रक्त',R,'red','standing',SS_EN,SS_HI,'sammend','Kaushambi','कौशाम्बी','kaushambi'],
[7,'Suparshvanatha','सुपार्श्वनाथ','','','Swastika','स्वस्तिक','swastika','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Varanasi','काशी','varanasi'],
[8,'Chandraprabha','चन्द्रप्रभ','','','Moon','चन्द्रमा','moon','White','श्वेत',W,'white','standing',SS_EN,SS_HI,'sammend','Chandrapuri','चन्द्रपुरी','chandrapuri'],
[9,'Pushpadanta','पुष्पदन्त','Suvidhinatha','सुविधिनाथ','Makara','मकर','makara','White','श्वेत',W,'white','standing',SS_EN,SS_HI,'sammend','Kakandi','काकन्दी','kakandi'],
[10,'Shitalanatha','शीतलनाथ','','','Shrivatsa','श्रीवत्स','shrivatsa','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Bhadrikapuri','भद्रिकापुरी','bhadrikapuri'],
[11,'Shreyansanatha','श्रेयांसनाथ','','','Rhinoceros','गैंडा','rhino','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Simhapuri','सिंहपुरी','simhapuri'],
[12,'Vasupujya','वासुपूज्य','','','Buffalo','महिष','buffalo','Red','रक्त',R,'red','standing','Champapuri','चम्पापुरी','champapuri','Champapuri','चम्पापुरी','champapuri'],
[13,'Vimalanatha','विमलनाथ','','','Boar','वराह','boar','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Kampilya','कम्पिल्या','kampilya'],
[14,'Anantanatha','अनन्तनाथ','','','Falcon','बाज़','falcon','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Ayodhya','अयोध्या','ayodhya'],
[15,'Dharmanatha','धर्मनाथ','','','Thunderbolt','वज्र','vajra','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Ratnapuri','रत्नपुरी','ratnapuri'],
[16,'Shantinatha','शान्तिनाथ','','','Deer','मृग','deer','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Hastinapur','हस्तिनापुर','hastinapur'],
[17,'Kunthunatha','कुन्थुनाथ','','','Goat','अज','goat','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Hastinapur','हस्तिनापुर','hastinapur'],
[18,'Aranatha','अरनाथ','','','Fish','मत्स्य','fish','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Hastinapur','हस्तिनापुर','hastinapur'],
[19,'Mallinatha','मल्लिनाथ','','','Water Pot','कलश','kalash','Blue','नील',B,'blue','standing',SS_EN,SS_HI,'sammend','Mathura','मथुरा','mathura'],
[20,'Munisuvrata','मुनिसुव्रत','','','Tortoise','कूर्म','tortoise','Dark','श्याम',D,'dark','standing',SS_EN,SS_HI,'sammend','Rajagriha','राजगृही','rajagriha'],
[21,'Naminatha','नामिनाथ','','','Blue Lotus','नील कमल','lotusBlue','Golden','स्वर्ण',G,'golden','standing',SS_EN,SS_HI,'sammend','Mithila','मिथिला','mithila'],
[22,'Neminatha','नेमिनाथ','Arishtanemi','अरिष्टनेमि','Conch','शंख','conch','Dark','श्याम',D,'dark','seated','Girnar','गिरनार','girnar','Shauripura','शौरिपुर','shauripura'],
[23,'Parshvanatha','पार्श्वनाथ','','','Serpent','सर्प','serpent','Blue','नील',B,'blue','standing',SS_EN,SS_HI,'sammend','Varanasi','काशी','varanasi'],
[24,'Mahavira','महावीर','Vardhamana','वर्धमान','Lion','सिंह','lion','Golden','स्वर्ण',G,'golden','seated','Pavapuri','पावापुरी','pavapuri','Kundagrama','कुण्डग्राम','kundagrama']
];

/* Where family or sectarian custom differs — shown as a note, never an answer. */
var T_NOTES = {
  10: { en:'Some Digambar charts give the Kalpavriksha (wish-fulfilling tree) instead.',
        hi:'कुछ दिगंबर चित्रों में श्रीवत्स के स्थान पर कल्पवृक्ष भी बताया जाता है।' },
  12: { en:'Some charts place his nirvana at Sammed Shikharji rather than Champapuri.',
        hi:'कुछ परंपराओं में इनका निर्वाण चम्पापुरी के स्थान पर सम्मेद शिखरजी बताया जाता है।' },
  14: { en:'Digambar charts sometimes give the porcupine (sahi) instead of the falcon.',
        hi:'दिगंबर चित्रों में कभी-कभी बाज़ के स्थान पर साही भी बताया जाता है।' },
  18: { en:'Some charts give the Nandyavarta instead of the fish.',
        hi:'कुछ चित्रों में मत्स्य के स्थान पर नन्द्यावर्त भी बताया जाता है।' }
};

var TIRTH = T_ROWS.map(function (r) {
  var note = T_NOTES[r[0]] || {};
  return {
    no: r[0], en: r[1], hi: r[2], aliasEn: r[3], aliasHi: r[4],
    chinhEn: r[5], chinhHi: r[6], chinhSvg: r[7],
    varnaEn: r[8], varnaHi: r[9], varnaHex: r[10], varnaKey: r[11],
    aasanKey: r[12],
    mokshaEn: r[13], mokshaHi: r[14], mokshaKey: r[15],
    janmaEn: r[16], janmaHi: r[17], janmaKey: r[18],
    noteEn: note.en || '', noteHi: note.hi || ''
  };
});

var ATTRS = ['chinh', 'varna', 'moksha', 'aasan', 'janma', 'mixed'];
var AASAN = {
  seated:   { en: 'Seated · Padmasana',    hi: 'पद्मासन · बैठे' },
  standing: { en: 'Standing · Kayotsarga', hi: 'कायोत्सर्ग · खड़े' }
};
var COUNTS = [4, 6, 8, 12];
var GAME_ID = 'memory-match';
var LB_KEY = 'jinbhakt:kids:leaderboard:v1';
var PREF_KEY = 'jinbhakt:kids:prefs:v1';
var LB_MAX = 20;


`;

const JS_CORE = `/* ============================================================
   CORE HELPERS · storage, i18n, formatting (all guarded)
   ============================================================ */
var $ = function (id) { return document.getElementById(id); };
var mem = {}, memOn = false;

function getLS() {
  try {
    if (typeof localStorage !== 'undefined' && localStorage) {
      localStorage.setItem('__p__', '1'); localStorage.removeItem('__p__');
      return localStorage;
    }
  } catch (e) { /* private mode */ }
  memOn = true;
  return null;
}
function rawGet(k) {
  var ls = getLS();
  try { if (ls) return ls.getItem(k); } catch (e) { /* ignore */ }
  return Object.prototype.hasOwnProperty.call(mem, k) ? mem[k] : null;
}
function rawSet(k, v) {
  var ls = getLS();
  try { if (ls) { ls.setItem(k, v); return true; } } catch (e) { /* ignore */ }
  try { mem[k] = v; } catch (e2) { return false; }
  return true;
}
function rawDel(k) {
  var ls = getLS();
  try { if (ls) ls.removeItem(k); } catch (e) { /* ignore */ }
  try { delete mem[k]; } catch (e2) { /* ignore */ }
}
function parseJSON(s, fb) {
  if (!s) return fb;
  try { var v = JSON.parse(s); return (v === null || v === undefined) ? fb : v; }
  catch (e) { return fb; }
}

function sanitizeName(raw) {
  var s = String(raw == null ? '' : raw);
  s = s.replace(/[\\u0000-\\u001f\\u007f]/g, '');
  s = s.replace(/[<>"'\`\\\\\\/]/g, '');
  s = s.replace(/\\s+/g, ' ').trim();
  if (s.length > 20) s = s.slice(0, 20).trim();
  return s;
}

var PREF_DEF = { lang: 'hi', aud: 'kids', sound: true, name: '', lastGame: '' };
function readPrefs() {
  var p = parseJSON(rawGet(PREF_KEY), {}), o = {};
  for (var k in PREF_DEF) {
    if (!Object.prototype.hasOwnProperty.call(PREF_DEF, k)) continue;
    o[k] = (p && p[k] !== undefined && p[k] !== null) ? p[k] : PREF_DEF[k];
  }
  o.lang = (o.lang === 'en') ? 'en' : 'hi';
  o.aud = (o.aud === 'adults') ? 'adults' : 'kids';
  o.sound = o.sound !== false;
  o.name = sanitizeName(o.name);
  return o;
}
function writePrefs(patch) {
  var c = readPrefs();
  if (patch) for (var k in patch) {
    if (Object.prototype.hasOwnProperty.call(patch, k) &&
        Object.prototype.hasOwnProperty.call(PREF_DEF, k)) c[k] = patch[k];
  }
  c.name = sanitizeName(c.name);
  rawSet(PREF_KEY, JSON.stringify(c));
  return c;
}

var DEV = ['\\u0966','\\u0967','\\u0968','\\u0969','\\u096A','\\u096B','\\u096C','\\u096D','\\u096E','\\u096F'];
function devNum(n) { return String(n).replace(/\\d/g, function (d) { return DEV[+d]; }); }
function fmtTime(sec) {
  var s = Math.max(0, Math.floor(sec || 0)), m = Math.floor(s / 60), r = s % 60;
  var out = m + ':' + (r < 10 ? '0' : '') + r;
  return S.lang === 'hi' ? devNum(out) : out;
}
function fmtClock(sec) {
  var s = Math.max(0, Math.floor(sec || 0));
  if (s < 3600) return fmtTime(s);
  var h = Math.floor(s / 3600);
  return S.lang === 'hi' ? devNum(h) + 'h ' + devNum(Math.floor((s % 3600) / 60)) + 'm'
                         : h + 'h ' + Math.floor((s % 3600) / 60) + 'm';
}
function t(key, vars) {
  var v = UI[S.lang] || UI.hi;
  var s = v[key];
  if (s === undefined) s = UI.hi[key];
  if (typeof s !== 'string') return s;
  if (!vars) return s;
  for (var k in vars) {
    if (!Object.prototype.hasOwnProperty.call(vars, k)) continue;
    s = s.split('{' + k + '}').join(String(vars[k]));
  }
  return s;
}
/** Pick the right language field off a data record. */
function L(obj, fieldHi, fieldEn) { return S.lang === 'hi' ? obj[fieldHi] : obj[fieldEn]; }

function shuffle(arr) {                 // Fisher-Yates, unbiased
  for (var i = arr.length - 1; i > 0; i--) {
    var j = Math.floor(Math.random() * (i + 1));
    var tmp = arr[i]; arr[i] = arr[j]; arr[j] = tmp;
  }
  return arr;
}
function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
function reduced() {
  try {
    return window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  } catch (e) { return false; }
}


/* ============================================================
   AUDIO · WebAudio only, created inside the first user gesture
   ============================================================ */
var AC = null;
function ac() {
  if (AC) return AC;
  try {
    var C = window.AudioContext || window.webkitAudioContext;
    if (!C) return null;
    AC = new C();
    if (AC.state === 'suspended' && AC.resume) AC.resume();
  } catch (e) { AC = null; }
  return AC;
}
function tone(freq, dur, type, gain, delay) {
  if (!S.sound) return;
  var c = ac(); if (!c) return;
  try {
    var t0 = c.currentTime + (delay || 0);
    var o = c.createOscillator(), g = c.createGain();
    o.type = type || 'sine';
    o.frequency.setValueAtTime(freq, t0);
    g.gain.setValueAtTime(0.0001, t0);
    g.gain.exponentialRampToValueAtTime(Math.max(0.0002, gain || 0.06), t0 + 0.015);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + (dur || 0.12));
    o.connect(g); g.connect(c.destination);
    o.start(t0); o.stop(t0 + (dur || 0.12) + 0.03);
  } catch (e) { /* audio is never fatal */ }
}
/** Temple bell: fundamental + two harmonics, long exponential decay. */
function bell(vol) {
  if (!S.sound) return;
  var v = (vol === undefined) ? 0.07 : vol;
  tone(392, 1.5, 'sine', v, 0);
  tone(588, 1.2, 'sine', v * 0.45, 0.01);
  tone(784, 0.9, 'sine', v * 0.25, 0.02);
}
var sfx = {
  tap:    function () { tone(660, 0.05, 'triangle', 0.035); },
  flip:   function () { tone(520, 0.07, 'sine', 0.045); },
  match:  function () { tone(659.25, 0.22, 'sine', 0.06, 0); tone(987.77, 0.34, 'sine', 0.05, 0.1); },
  miss:   function () { tone(233, 0.16, 'sine', 0.04); },
  finish: function () { bell(0.08); tone(523.25, 0.5, 'sine', 0.05, 0.35); }
};

/* ============================================================
   SVG ART · generated at runtime, no images, no icon fonts
   ============================================================ */
function svgWrap(inner, vb, title) {
  var a = title
    ? 'role="img" aria-label="' + title.replace(/"/g, '') + '"'
    : 'aria-hidden="true" focusable="false"';
  return '<svg viewBox="0 0 ' + (vb || 64) + ' ' + (vb || 64) + '" ' + a +
         ' xmlns="http://www.w3.org/2000/svg">' + inner + '</svg>';
}
/* Jain Swastika — four arms, three dots (ratnatraya) and the siddhashila
   crescent-and-dot above. Drawn from paths so no font can ever mirror it. */
function artSwastika(title) {
  var s = 'fill="none" stroke="currentColor" stroke-width="4.6" stroke-linecap="square"';
  var arms =
    '<path ' + s + ' d="M26 22 H42 V38"/>' +
    '<path ' + s + ' d="M42 26 V42 H26"/>' +
    '<path ' + s + ' d="M38 42 H22 V26"/>' +
    '<path ' + s + ' d="M22 38 V22 H38"/>';
  var dots = '<circle cx="26" cy="52" r="2.3" fill="currentColor"/>' +
             '<circle cx="32" cy="54.4" r="2.3" fill="currentColor"/>' +
             '<circle cx="38" cy="52" r="2.3" fill="currentColor"/>';
  var cres = '<path d="M22 12 A12 12 0 0 0 42 12 A10 10 0 0 1 22 12 Z" fill="currentColor"/>' +
             '<circle cx="32" cy="5.4" r="2.4" fill="currentColor"/>';
  return svgWrap('<g transform="translate(0,2)">' + arms + '</g>' + dots + cres, 64, title);
}
/* 8-fold radially symmetric lotus rosette — mirroring is invisible by design. */
function artRosette(title) {
  var p = '';
  for (var i = 0; i < 8; i++) {
    p += '<path d="M32 32 C24 22 24 12 32 5 C40 12 40 22 32 32 Z" fill="currentColor" ' +
         'opacity="' + (i % 2 ? '.38' : '.62') + '" transform="rotate(' + (i * 45) + ' 32 32)"/>';
  }
  p += '<circle cx="32" cy="32" r="6.4" fill="none" stroke="currentColor" stroke-width="2"/>';
  p += '<circle cx="32" cy="32" r="2.6" fill="currentColor"/>';
  return svgWrap(p, 64, title);
}
function artDiya(title) {
  return svgWrap(
    '<path d="M12 40 C12 50 22 56 32 56 C42 56 52 50 52 40 Z" fill="currentColor" opacity=".85"/>' +
    '<ellipse cx="32" cy="40" rx="20" ry="4.6" fill="currentColor"/>' +
    '<path d="M32 14 C37 22 39 27 39 31 A7 7 0 0 1 25 31 C25 27 27 22 32 14 Z" ' +
    'fill="currentColor" opacity=".62"/>', 64, title);
}
function artBell(on, title) {
  var body = '<path d="M32 10 C22 10 18 19 18 29 C18 38 15 42 13 45 H51 C49 42 46 38 46 29 ' +
             'C46 19 42 10 32 10 Z" fill="none" stroke="currentColor" stroke-width="3.4"/>' +
             '<path d="M26 50 A6 6 0 0 0 38 50" fill="none" stroke="currentColor" stroke-width="3.4"/>' +
             '<circle cx="32" cy="7.6" r="2.6" fill="currentColor"/>';
  if (!on) body += '<path d="M10 56 L54 12" stroke="currentColor" stroke-width="3.6" stroke-linecap="round"/>';
  return svgWrap(body, 64, title);
}
function artMedal(title) {
  return svgWrap(
    '<circle cx="32" cy="38" r="18" fill="none" stroke="currentColor" stroke-width="3.2"/>' +
    '<path d="M22 6 L28 22 M42 6 L36 22" stroke="currentColor" stroke-width="4" ' +
    'stroke-linecap="round" fill="none"/>' +
    '<path d="M32 29 L34.6 35.4 L41.4 35.9 L36.2 40.3 L37.8 47 L32 43.4 L26.2 47 L27.8 40.3 ' +
    'L22.6 35.9 L29.4 35.4 Z" fill="currentColor"/>', 64, title);
}


/* ---- the 24 lanchan (emblems) as simple line art ---- */
var STK = 'fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"';
var EMBLEM = {
  bull:      '<path ' + STK + ' d="M18 20 C10 14 8 24 14 30 M46 20 C54 14 56 24 50 30"/>' +
             '<path ' + STK + ' d="M20 26 C20 44 26 52 32 52 C38 52 44 44 44 26 Z"/>' +
             '<circle cx="26" cy="36" r="2" fill="currentColor"/><circle cx="38" cy="36" r="2" fill="currentColor"/>',
  elephant:  '<path ' + STK + ' d="M16 24 C8 22 8 40 18 42 M48 24 C56 22 56 40 46 42"/>' +
             '<path ' + STK + ' d="M20 24 C20 14 44 14 44 24 C44 34 42 40 40 44"/>' +
             '<path ' + STK + ' d="M40 44 C44 50 40 56 34 54 C30 53 30 48 33 47"/>',
  horse:     '<path ' + STK + ' d="M22 52 C20 38 22 26 30 20 C36 16 44 18 46 24 C48 30 44 34 40 34"/>' +
             '<path ' + STK + ' d="M30 20 C26 14 22 12 18 14 C22 18 22 22 22 26"/>' +
             '<circle cx="38" cy="25" r="2" fill="currentColor"/>',
  monkey:    '<circle cx="32" cy="34" r="14" ' + STK + '/>' +
             '<circle cx="15" cy="30" r="6" ' + STK + '/><circle cx="49" cy="30" r="6" ' + STK + '/>' +
             '<path ' + STK + ' d="M25 30 C27 26 37 26 39 30 C40 38 36 44 32 44 C28 44 24 38 25 30 Z"/>' +
             '<circle cx="28" cy="34" r="1.8" fill="currentColor"/><circle cx="36" cy="34" r="1.8" fill="currentColor"/>',
  curlew:    '<path ' + STK + ' d="M14 44 C22 30 38 24 52 22"/>' +
             '<path ' + STK + ' d="M52 22 C46 30 40 34 34 36"/>' +
             '<path ' + STK + ' d="M24 40 C28 48 36 52 44 50"/>' +
             '<circle cx="48" cy="25" r="2" fill="currentColor"/>',
  lotusRed:  '<path ' + STK + ' d="M32 48 C20 44 14 34 14 26 C22 26 28 32 32 40 C36 32 42 26 50 26 C50 34 44 44 32 48 Z"/>' +
             '<path ' + STK + ' d="M32 40 C30 30 30 20 32 12 C34 20 34 30 32 40 Z"/>',
  swastika:  '<path ' + STK + ' d="M26 22 H42 V38"/><path ' + STK + ' d="M42 26 V42 H26"/>' +
             '<path ' + STK + ' d="M38 42 H22 V26"/><path ' + STK + ' d="M22 38 V22 H38"/>' +
             '<circle cx="26" cy="52" r="2" fill="currentColor"/><circle cx="32" cy="54" r="2" fill="currentColor"/>' +
             '<circle cx="38" cy="52" r="2" fill="currentColor"/>',
  moon:      '<path ' + STK + ' d="M42 12 A22 22 0 1 0 42 52 A17 17 0 1 1 42 12 Z"/>',
  makara:    '<path ' + STK + ' d="M10 38 C18 28 30 26 40 30 C46 32 50 30 54 24"/>' +
             '<path ' + STK + ' d="M10 38 C18 48 32 50 42 44 C48 40 52 42 54 48"/>' +
             '<path ' + STK + ' d="M40 30 L44 22 L48 30"/>' +
             '<circle cx="20" cy="35" r="2" fill="currentColor"/>',
  shrivatsa: '<path ' + STK + ' d="M32 12 L50 32 L32 52 L14 32 Z"/>' +
             '<path ' + STK + ' d="M32 22 L41 32 L32 42 L23 32 Z"/>',
  rhino:     '<path ' + STK + ' d="M16 46 C14 32 22 22 34 22 C44 22 50 30 50 40 C50 46 46 50 40 50 L20 50 Z"/>' +
             '<path ' + STK + ' d="M46 30 L56 20 L52 34"/>' +
             '<circle cx="26" cy="36" r="2.2" fill="currentColor"/>',
  buffalo:   '<path ' + STK + ' d="M14 24 C6 22 6 36 16 38 M50 24 C58 22 58 36 48 38"/>' +
             '<path ' + STK + ' d="M18 28 C18 18 46 18 46 28 C46 42 40 52 32 52 C24 52 18 42 18 28 Z"/>' +
             '<circle cx="26" cy="36" r="2" fill="currentColor"/><circle cx="38" cy="36" r="2" fill="currentColor"/>',
  boar:      '<path ' + STK + ' d="M14 40 C14 26 26 20 38 22 C48 24 54 32 52 42 C50 50 40 54 30 52 C20 50 14 46 14 40 Z"/>' +
             '<path ' + STK + ' d="M50 34 L58 30 L54 40"/><path ' + STK + ' d="M44 46 C48 50 52 50 54 46"/>' +
             '<circle cx="26" cy="34" r="2" fill="currentColor"/>',
  falcon:    '<path ' + STK + ' d="M12 30 C22 18 42 16 52 26 C46 28 42 32 40 38 C34 34 26 32 20 34 Z"/>' +
             '<path ' + STK + ' d="M52 26 L58 30 L50 32"/>' +
             '<circle cx="44" cy="24" r="2" fill="currentColor"/>',
  vajra:     '<path ' + STK + ' d="M36 8 L20 34 H30 L26 56 L46 28 H34 Z"/>',
  deer:      '<path ' + STK + ' d="M24 24 C20 14 14 12 10 14 M24 24 C24 14 28 10 32 10"/>' +
             '<path ' + STK + ' d="M40 24 C44 14 50 12 54 14 M40 24 C40 14 36 10 32 10"/>' +
             '<path ' + STK + ' d="M22 30 C22 24 42 24 42 30 C42 44 38 54 32 54 C26 54 22 44 22 30 Z"/>' +
             '<circle cx="27" cy="36" r="2" fill="currentColor"/><circle cx="37" cy="36" r="2" fill="currentColor"/>',
  goat:      '<path ' + STK + ' d="M22 26 C14 22 10 14 12 8 M42 26 C50 22 54 14 52 8"/>' +
             '<path ' + STK + ' d="M22 28 C22 20 42 20 42 28 C42 42 38 54 32 54 C26 54 22 42 22 28 Z"/>' +
             '<path ' + STK + ' d="M30 54 C30 58 34 58 34 54"/>' +
             '<circle cx="27" cy="34" r="2" fill="currentColor"/><circle cx="37" cy="34" r="2" fill="currentColor"/>',
  fish:      '<path ' + STK + ' d="M10 32 C18 20 38 18 48 32 C38 46 18 44 10 32 Z"/>' +
             '<path ' + STK + ' d="M48 32 L58 22 V42 Z"/>' +
             '<circle cx="20" cy="30" r="2.2" fill="currentColor"/>',
  kalash:    '<path ' + STK + ' d="M22 26 H42 L46 34 C48 44 42 54 32 54 C22 54 16 44 18 34 Z"/>' +
             '<path ' + STK + ' d="M26 26 C26 18 38 18 38 26"/>' +
             '<path ' + STK + ' d="M32 18 V10"/><circle cx="32" cy="8" r="2.6" fill="currentColor"/>',
  tortoise:  '<path ' + STK + ' d="M12 40 C12 26 22 18 32 18 C42 18 52 26 52 40 Z"/>' +
             '<path ' + STK + ' d="M32 18 V40 M18 30 L46 30 M14 38 L50 38"/>' +
             '<path ' + STK + ' d="M12 40 H52"/>' +
             '<path ' + STK + ' d="M18 40 L14 50 M46 40 L50 50 M32 40 V50"/>',
  lotusBlue: '<path ' + STK + ' d="M32 50 C18 46 12 34 12 24 C22 24 28 32 32 42 C36 32 42 24 52 24 C52 34 46 46 32 50 Z"/>' +
             '<path ' + STK + ' d="M32 42 C29 30 29 18 32 10 C35 18 35 30 32 42 Z"/>' +
             '<circle cx="32" cy="46" r="2" fill="currentColor"/>',
  conch:     '<path ' + STK + ' d="M20 46 C12 38 14 22 28 18 C42 14 54 24 52 36 C50 46 40 52 32 48"/>' +
             '<path ' + STK + ' d="M26 40 C22 34 26 26 34 26 C40 26 44 32 42 38"/>' +
             '<path ' + STK + ' d="M20 46 L14 54 L26 50"/>',
  serpent:   '<path ' + STK + ' d="M18 52 C14 40 16 26 24 20 C30 16 38 16 44 22 C50 28 50 40 46 52"/>' +
             '<path ' + STK + ' d="M24 20 C26 12 38 12 40 20"/>' +
             '<circle cx="28" cy="26" r="2" fill="currentColor"/><circle cx="36" cy="26" r="2" fill="currentColor"/>' +
             '<path ' + STK + ' d="M30 34 H34"/>',
  lion:      '<path ' + STK + ' d="M32 10 L38 18 L48 16 L46 26 L54 32 L46 38 L48 48 L38 46 L32 54 L26 46 L16 48 L18 38 L10 32 L18 26 L16 16 L26 18 Z"/>' +
             '<circle cx="32" cy="32" r="9" ' + STK + '/>' +
             '<circle cx="28.5" cy="30" r="1.8" fill="currentColor"/><circle cx="35.5" cy="30" r="1.8" fill="currentColor"/>'
};
function artEmblem(key, title) {
  return svgWrap(EMBLEM[key] || EMBLEM.lotusRed, 64, title);
}


/* ---- attribute art: complexion, posture, nirvana place, birth place ---- */
function artDisc(hex, title) {
  return svgWrap(
    '<circle cx="32" cy="32" r="21" fill="' + hex + '" stroke="#8A6A2A" stroke-width="2.4"/>' +
    '<circle cx="32" cy="32" r="21" fill="none" stroke="rgba(255,255,255,.55)" stroke-width="1.2"/>' +
    '<ellipse cx="25" cy="24" rx="7" ry="5" fill="rgba(255,255,255,.34)" transform="rotate(-28 25 24)"/>',
    64, title);
}
/* Abstract, faceless meditative figure — no facial features, ever. */
function artSilhouette(kind, title) {
  var body;
  if (kind === 'seated') {
    body = '<circle cx="32" cy="16" r="7" fill="currentColor" opacity=".88"/>' +
           '<path d="M32 24 C22 24 16 32 15 42 L49 42 C48 32 42 24 32 24 Z" fill="currentColor" opacity=".88"/>' +
           '<path d="M10 44 C16 50 48 50 54 44 L54 50 C48 56 16 56 10 50 Z" fill="currentColor" opacity=".62"/>';
  } else {
    body = '<circle cx="32" cy="11" r="6.4" fill="currentColor" opacity=".88"/>' +
           '<path d="M32 18 C25 18 21 24 21 32 L21 46 L26 46 L26 58 L38 58 L38 46 L43 46 L43 32 ' +
           'C43 24 39 18 32 18 Z" fill="currentColor" opacity=".88"/>' +
           '<path d="M17 30 L21 30 M43 30 L47 30" stroke="currentColor" stroke-width="3" stroke-linecap="round"/>';
  }
  return svgWrap(body, 64, title);
}
/* Five distinct hill-and-temple skylines, one per nirvana sthal. */
var MOKSHA_ART = {
  sammend:    '<path d="M4 56 L18 22 L26 40 L34 12 L44 38 L52 24 L60 56 Z" fill="currentColor" opacity=".8"/>' +
              '<path d="M30 40 h8 v16 h-8 Z" fill="#FFF8F0" opacity=".75"/>',
  ashtapada:  '<path d="M4 56 L14 30 L22 44 L32 16 L42 44 L50 30 L60 56 Z" fill="currentColor" opacity=".8"/>' +
              '<circle cx="32" cy="12" r="4" fill="currentColor"/>',
  champapuri: '<path d="M6 56 V34 H20 V56 Z M44 56 V34 H58 V56 Z" fill="currentColor" opacity=".72"/>' +
              '<path d="M22 56 V26 H42 V56 Z" fill="currentColor" opacity=".88"/>' +
              '<path d="M26 26 C26 16 38 16 38 26 Z" fill="currentColor"/>' +
              '<path d="M32 12 V6" stroke="currentColor" stroke-width="2.6"/>',
  girnar:     '<path d="M2 56 L16 18 L28 42 L38 10 L50 40 L62 56 Z" fill="currentColor" opacity=".82"/>' +
              '<path d="M34 30 h8 v10 h-8 Z" fill="#FFF8F0" opacity=".8"/>',
  pavapuri:   '<path d="M4 56 C16 48 20 34 32 34 C44 34 48 48 60 56 Z" fill="currentColor" opacity=".55"/>' +
              '<path d="M24 56 V36 H40 V56 Z" fill="currentColor" opacity=".88"/>' +
              '<path d="M26 36 C26 24 38 24 38 36 Z" fill="currentColor"/>' +
              '<path d="M10 56 H54" stroke="#FFF8F0" stroke-width="2.4" opacity=".7"/>'
};
function artMoksha(key, title) {
  return svgWrap(MOKSHA_ART[key] || MOKSHA_ART.sammend, 64, title);
}
function artGate(title) {
  return svgWrap(
    '<path d="M10 56 V26 H54 V56" fill="none" stroke="currentColor" stroke-width="3.4"/>' +
    '<path d="M22 56 V36 C22 28 42 28 42 36 V56" fill="none" stroke="currentColor" stroke-width="3.2"/>' +
    '<path d="M6 26 L32 10 L58 26" fill="none" stroke="currentColor" stroke-width="3.4"/>' +
    '<circle cx="32" cy="20" r="3" fill="currentColor"/>' +
    '<path d="M14 30 V56 M50 30 V56" stroke="currentColor" stroke-width="2" opacity=".6"/>',
    64, title);
}
/* The art shown on an attribute card, by attribute key. */
function attrArt(attr, th) {
  var title = '';
  if (attr === 'chinh')  return artEmblem(th.chinhSvg, L(th, 'chinhHi', 'chinhEn'));
  if (attr === 'varna')  return artDisc(th.varnaHex, L(th, 'varnaHi', 'varnaEn'));
  if (attr === 'moksha') return artMoksha(th.mokshaKey, L(th, 'mokshaHi', 'mokshaEn'));
  if (attr === 'aasan')  return artSilhouette(th.aasanKey, AASAN[th.aasanKey][S.lang]);
  if (attr === 'janma')  return artGate(L(th, 'janmaHi', 'janmaEn'));
  return artRosette(title);
}
/* The text label shown under the attribute art. */
function attrText(attr, th) {
  if (attr === 'chinh')  return L(th, 'chinhHi', 'chinhEn');
  if (attr === 'varna')  return L(th, 'varnaHi', 'varnaEn');
  if (attr === 'moksha') return L(th, 'mokshaHi', 'mokshaEn');
  if (attr === 'aasan')  return AASAN[th.aasanKey][S.lang];
  if (attr === 'janma')  return L(th, 'janmaHi', 'janmaEn');
  return '';
}
/* One-line teaching fact spoken on a successful match. */
function factLine(th, attr) {
  var name = L(th, 'hi', 'en');
  var parts = [name, attrText(attr, th)];
  if (attr !== 'moksha') parts.push(L(th, 'mokshaHi', 'mokshaEn'));
  return parts.join(' · ');
}


`;

const JS_SHELL = `/* ============================================================
   TOAST / DIALOG / PARTICLES
   ============================================================ */
var toastId = null;
function toast(msg) {
  var el = $('toast');
  el.textContent = msg;
  el.classList.add('is-on');
  if (toastId) clearTimeout(toastId);
  toastId = setTimeout(function () { el.classList.remove('is-on'); }, 3200);
}
function say(msg) { var el = $('live'); if (el) el.textContent = msg; }

var dlgYesFn = null, dlgLastFocus = null;
function askDialog(title, body, yesLabel, noLabel, onYes) {
  dlgLastFocus = document.activeElement;
  $('dlgTitle').textContent = title;
  $('dlgBody').textContent = body;
  $('dlgYes').textContent = yesLabel;
  $('dlgNo').textContent = noLabel;
  dlgYesFn = onYes;
  $('dialog').classList.remove('is-hidden');
  $('dlgNo').focus();
}
function closeDialog() {
  $('dialog').classList.add('is-hidden');
  dlgYesFn = null;
  if (dlgLastFocus && dlgLastFocus.focus) dlgLastFocus.focus();
}
$('dlgYes').addEventListener('click', function () { var f = dlgYesFn; closeDialog(); if (f) f(); });
$('dlgNo').addEventListener('click', closeDialog);
$('dialog').addEventListener('click', function (e) { if (e.target === $('dialog')) closeDialog(); });
document.addEventListener('keydown', function (e) {
  if (e.key === 'Escape' && !$('dialog').classList.contains('is-hidden')) closeDialog();
});

/** Muted marigold petals — transform + opacity only, skipped for reduced motion. */
function petals(count) {
  if (reduced()) return;
  var host = $('fx');
  var cols = ['#E8800C', '#C8860A', '#B23A3A', '#D4A574', '#E3B23C'];
  var n = count || 24;
  for (var i = 0; i < n; i++) {
    var p = document.createElement('i');
    var size = 7 + Math.random() * 8;
    p.style.left = (Math.random() * 100) + 'vw';
    p.style.width = size + 'px';
    p.style.height = (size * 1.35) + 'px';
    p.style.background = cols[i % cols.length];
    p.style.opacity = '.8';
    p.style.animationDuration = (2.6 + Math.random() * 2.2) + 's';
    p.style.animationDelay = (Math.random() * 0.7) + 's';
    host.appendChild(p);
    (function (node) { setTimeout(function () { if (node.parentNode) node.parentNode.removeChild(node); }, 5600); })(p);
  }
}

/* ============================================================
   LEADERBOARD · shared schema, one key for all six games
   ============================================================ */
function lbAll() {
  var o = parseJSON(rawGet(LB_KEY), {});
  return (o && typeof o === 'object' && !Array.isArray(o)) ? o : {};
}
function lbList() {
  var l = lbAll()[GAME_ID];
  if (!Array.isArray(l)) return [];
  var out = [];
  for (var i = 0; i < l.length; i++) {
    var e = l[i];
    if (!e || typeof e !== 'object') continue;
    out.push({
      name: sanitizeName(e.name), level: String(e.level || ''), levelKey: String(e.levelKey || ''),
      duration: Math.max(0, Math.floor(Number(e.duration) || 0)),
      score: Math.max(0, Math.floor(Number(e.score) || 0)),
      meta: (e.meta && typeof e.meta === 'object') ? e.meta : {},
      ts: Math.floor(Number(e.ts) || Date.now())
    });
  }
  out.sort(lbCmp);
  return out;
}
function lbCmp(a, b) { return LB_CMP(a, b); }
function lbSave(entry) {
  var all = lbAll();
  var list = Array.isArray(all[GAME_ID]) ? all[GAME_ID] : [];
  list.push(entry);
  list.sort(lbCmp);
  if (list.length > LB_MAX) list = list.slice(0, LB_MAX);
  all[GAME_ID] = list;
  var okSave = rawSet(LB_KEY, JSON.stringify(all));
  var rank = 0;
  for (var i = 0; i < list.length; i++) {
    if (list[i].ts === entry.ts && list[i].name === entry.name &&
        list[i].levelKey === entry.levelKey) { rank = i + 1; break; }
  }
  return { saved: okSave, rank: rank };
}
function lbClear() {
  var all = lbAll();
  if (Object.prototype.hasOwnProperty.call(all, GAME_ID)) {
    delete all[GAME_ID];
    rawSet(LB_KEY, JSON.stringify(all));
  }
}


`;

module.exports = { CSS_BASE, JS_TIRTH, JS_CORE, JS_SHELL };
