/* ============================================================
   UI DICTIONARY · shared by the wheel and the lotus ritual.
   Every visible string lives here; nothing is hardcoded outside.
   ============================================================ */
var UI = {
  en: {
    brandHi: 'नियम', brandEn: 'Daily Vow',
    langSwitch: 'हिंदी', hub: 'All games', restart: 'Restart',
    soundOn: 'Sound on', soundOff: 'Sound off',
    s1Title: 'Choose your language', s1Sub: 'अपनी भाषा चुनिए',
    s2Title: 'Who is taking the vow today?',
    s2Sub: 'Two separate lists of niyams, each written for its own age.',
    kids: 'Kids', kidsNote: 'Baalak', adults: 'Adults', adultsNote: 'Vyask',
    catTitle: 'Choose a category of niyam — or let it choose',
    any: 'Any category',
    wheelSpin: 'My daily vow — turn the wheel',
    wheelTurning: 'Turning…',
    lotusBloom: 'Let the lotus open',
    lotusBlooming: 'Opening…',
    hintIdle: 'Settle the breath, then begin. One vow is enough for one day.',
    hintKids: 'Tap to receive today’s niyam.',
    hintBreath: 'Breathe in slowly as it opens…',
    meta: '{n} niyams in this list · {who}',
    whoKids: 'Kids', whoAdults: 'Adults',
    resTitle: 'Your niyam for today',
    labP: 'Pratigya · my vow', labT: 'Tyaag · I give up', catLbl: 'Category',
    accept: 'I accept this vow', accepted: 'Vow accepted today',
    again: 'Draw again', list: 'See the full list', hideList: 'Hide the list',
    listTitle: 'The full list of niyams ({who}) · {n}',
    streak: 'Streak · {n} day(s)',
    cheers: ['Sadhu! Sadhu! A fine vow for today.',
             'Sadhu! Small restraints build a great soul.',
             'Well taken. Carry it with a quiet, smiling heart.',
             'Sadhu! Sadhu! Your day now has a clear direction.',
             'Beautiful. Restraint is a lamp lit within.'],
    toastAcc: 'Vow recorded · Sadhu! Sadhu!',
    toastStreak: 'Streak · {n} day(s)',
    rankLine: 'You are #{n} on this device',
    lbTitle: 'Leaderboard · most vows kept', lbClear: 'Clear',
    lbEmpty: 'No records yet. Be the first!',
    lbConfirmTitle: 'Clear the leaderboard?',
    lbConfirmBody: 'Every record for this game will be removed from this device.',
    lbConfirmYes: 'Yes, clear them', lbConfirmNo: 'Keep them',
    lbCleared: 'Records cleared.',
    thRank: '#', thLbName: 'Name', thLbLevel: 'Level', thLbTime: 'Time', thLbVows: 'Vows',
    nameLabel: 'Your name (kept on this device only)', namePh: 'e.g. Vraddhim',
    nameOptional: 'A name is optional — leave it blank to play quietly.',
    statVows: 'Vows taken', statStreak: 'Day streak', statTime: 'Time here', statCat: 'Categories',
    reviewTitle: 'Vows accepted today',
    noVowsYet: 'No vow accepted yet today.',
    storageOff: 'Records cannot be saved in a private window — the vows still work.',
    saved: 'Saved to this device',
    foot: 'Rooted in the Digambar Jain tradition of daily niyam. Practices vary by family and lineage — always ask your elders.'
  },
  hi: {
    brandHi: 'नियम', brandEn: 'Daily Vow',
    langSwitch: 'English', hub: 'सभी खेल', restart: 'पुनः आरंभ',
    soundOn: 'ध्वनि चालू', soundOff: 'ध्वनि बंद',
    s1Title: 'अपनी भाषा चुनिए', s1Sub: 'Choose your language',
    s2Title: 'आज संकल्प कौन ले रहा है?',
    s2Sub: 'बालक और व्यस्क के लिए अलग-अलग लिखी गई दो नियम-सूचियाँ।',
    kids: 'बालक', kidsNote: 'Baalak', adults: 'व्यस्क', adultsNote: 'Vyask',
    catTitle: 'नियम की श्रेणी चुनिए — या चुनने दीजिए',
    any: 'कोई भी श्रेणी',
    wheelSpin: 'आज का नियम — चक्र घुमाइए',
    wheelTurning: 'घूम रहा है…',
    lotusBloom: 'कमल खिलने दीजिए',
    lotusBlooming: 'खिल रहा है…',
    hintIdle: 'श्वास स्थिर कीजिए, फिर आरंभ कीजिए। एक दिन हेतु एक नियम ही पर्याप्त है।',
    hintKids: 'आज का नियम पाने के लिए छूइए।',
    hintBreath: 'खिलते हुए धीरे श्वास भीतर लीजिए…',
    meta: 'इस सूची में {n} नियम · {who}',
    whoKids: 'बालक', whoAdults: 'व्यस्क',
    resTitle: 'आपका आज का नियम',
    labP: 'प्रतिज्ञा · मेरा संकल्प', labT: 'त्याग · मैं छोड़ता हूँ', catLbl: 'श्रेणी',
    accept: 'मैं यह नियम स्वीकार करता हूँ', accepted: 'आज का नियम स्वीकृत',
    again: 'पुनः लीजिए', list: 'पूर्ण सूची देखिए', hideList: 'सूची छिपाइए',
    listTitle: 'नियमों की पूर्ण सूची ({who}) · {n}',
    streak: 'क्रम · {n} दिन',
    cheers: ['साधु! साधु! आज हेतु उत्तम संकल्प।',
             'साधु! छोटे-छोटे संयम ही महान आत्मा बनाते हैं।',
             'उत्तम ग्रहण। इस संकल्प को शांत, प्रसन्न मन से धारण कीजिए।',
             'साधु! साधु! आपका दिन अब एक स्पष्ट दिशा पा गया।',
             'अद्भुत। संयम भीतर जलता हुआ दीपक है।'],
    toastAcc: 'संकल्प दर्ज हुआ · साधु! साधु!',
    toastStreak: 'क्रम · {n} दिन',
    rankLine: 'इस उपकरण पर आप #{n} स्थान पर हैं',
    lbTitle: 'उपलब्धि सूची · सर्वाधिक नियम', lbClear: 'हटाइए',
    lbEmpty: 'अभी कोई रिकॉर्ड नहीं। पहले बनिए!',
    lbConfirmTitle: 'उपलब्धि सूची हटाएँ?',
    lbConfirmBody: 'इस खेल के सभी रिकॉर्ड इस उपकरण से हट जाएँगे।',
    lbConfirmYes: 'हाँ, हटा दीजिए', lbConfirmNo: 'रहने दीजिए',
    lbCleared: 'रिकॉर्ड हटा दिए गए।',
    thRank: '#', thLbName: 'नाम', thLbLevel: 'स्तर', thLbTime: 'समय', thLbVows: 'नियम',
    nameLabel: 'आपका नाम (केवल इसी उपकरण में संचित)', namePh: 'जैसे वृद्धिम',
    nameOptional: 'नाम आवश्यक नहीं — शांति से खेलने हेतु खाली छोड़ दीजिए।',
    statVows: 'गृहीत नियम', statStreak: 'दिनों का क्रम', statTime: 'यहाँ बिताया समय', statCat: 'श्रेणियाँ',
    reviewTitle: 'आज स्वीकार किए नियम',
    noVowsYet: 'आज अभी कोई नियम स्वीकार नहीं हुआ।',
    storageOff: 'निजी विंडो में रिकॉर्ड संचित नहीं हो सकते — संकल्प फिर भी मान्य हैं।',
    saved: 'इस उपकरण में संचित हुआ',
    foot: 'दिगंबर जैन परंपरा के दैनिक नियमों में निहित। आचरण परिवार और परंपरा अनुसार भिन्न हो सकते हैं — अपने बड़ों से अवश्य पूछिए।'
  }
};
