/* ============================================================
   UI DICTIONARY · every visible string lives here
   ============================================================ */
var UI = {
  en: {
    brandHi: 'सात्त्विक रसोई', brandEn: 'Sattvic Chef',
    langSwitch: 'हिंदी', hub: 'All games', restart: 'Restart',
    soundOn: 'Sound on', soundOff: 'Sound off',
    s1Title: 'Choose your language', s1Sub: 'अपनी भाषा चुनिए',
    s2Title: 'Whose kitchen is this?',
    s2Sub: 'The children’s round covers everyday foods. The adults’ round adds the stricter observances — anantkāy, one-seeded fruits, fermented food and stored food.',
    kids: 'Kids', kidsNote: 'Baalak · everyday foods',
    adults: 'Adults', adultsNote: 'Vyask · stricter observances',
    s3Title: 'Set up your round',
    s3Sub: 'Choose how many foods you want to sort.',
    nameLabel: 'Your name (kept on this device only)', namePh: 'e.g. Vraddhim',
    roundLabel: 'How many foods?', roundAll: 'All of them',
    start: 'Begin', leaderboard: 'Leaderboard',
    setupHint: 'Drag the food into a basket, swipe it left or right, tap a basket, or press 1 for Jain-friendly and 2 for not.',
    nameNeeded: 'Please write your name first.',
    binYes: 'Jain-friendly', binYesNote: 'Sāttvic and ahimsa-safe',
    binNo: 'Not Jain-friendly', binNoNote: 'Avoided in a Jain diet',
    binYesArrow: '← drag or press 1', binNoArrow: 'drag or press 2 →',
    cardHint: 'Drag me, swipe me, or tap a basket',
    hudScore: 'Points', hudStreak: 'Streak', hudCount: 'Sorted',
    verdictYes: 'is JAIN-FRIENDLY', verdictNo: 'is NOT Jain-friendly',
    correct: 'Shabash! That is right.',
    wrong: 'Not quite — here is the lesson.',
    points: '+{n} points',
    keepLearning: 'Keep learning',
    next: 'Next',
    noteLabel: 'Family note',
    quit: 'Leave this round',
    quitConfirm: 'Leave this round?', quitBody: 'Your progress in this round will be lost.',
    yes: 'Yes, leave', no: 'Keep playing',
    resTitle: ['Curious learner', 'Ahimsa apprentice', 'Sattvic chef', 'Param sattvic chef'],
    resSub: ['Every great chef starts somewhere. Sort a few more foods.',
             'Well done — a little more practice and this will be second nature.',
             'Wonderful. Your kitchen is full of ahimsa.',
             'Perfect. You know the Jain diet inside out.'],
    statScore: 'Points', statCorrect: 'Correct', statBest: 'Best streak', statTime: 'Time',
    rankLine: 'You are #{n} on this device',
    cheers: ['Sadhu! Sadhu! Ahimsa begins at the kitchen door.',
             'Well done — care in eating is care for every living being.',
             'Sadhu! Each right choice was a small act of kindness.',
             'Beautiful. A sāttvic table is a quiet form of worship.',
             'Sadhu! Sadhu! You sorted with a steady mind.'],
    again: 'Play again', changeSetup: 'Change set-up', showLb: 'Leaderboard',
    reviewTitle: 'What you learned today',
    reviewEmpty: 'Nothing was missed — here are four to remember.',
    lbTitle: 'Leaderboard · highest scores', lbClear: 'Clear',
    lbEmpty: 'No records yet. Be the first!',
    lbConfirmTitle: 'Clear the leaderboard?',
    lbConfirmBody: 'Every record for this game will be removed from this device.',
    lbCleared: 'Records cleared.',
    thRank: '#', thLbName: 'Name', thLbLevel: 'Level', thLbTime: 'Time', thLbScore: 'Points',
    storageOff: 'Records cannot be saved in a private window — the game still plays.',
    saved: 'Round saved · {n} points',
    foot: 'Based on traditional Digambar Jain dietary principles of ahimsa. Practice varies by family and tradition — always ask your elders.'
  },
  hi: {
    brandHi: 'सात्त्विक रसोई', brandEn: 'Sattvic Chef',
    langSwitch: 'English', hub: 'सभी खेल', restart: 'पुनः आरंभ',
    soundOn: 'ध्वनि चालू', soundOff: 'ध्वनि बंद',
    s1Title: 'अपनी भाषा चुनिए', s1Sub: 'Choose your language',
    s2Title: 'यह किसकी रसोई है?',
    s2Sub: 'बालकों की बारी में रोज़मर्रा के भोजन हैं। व्यस्कों की बारी में कड़े अनुष्ठान भी जुड़ते हैं — अनंतकाय, एक-बीज फल, किण्वित और संचित भोजन।',
    kids: 'बालक', kidsNote: 'रोज़मर्रा के भोजन',
    adults: 'व्यस्क', adultsNote: 'कड़े अनुष्ठान सहित',
    s3Title: 'अपनी बारी सजाइए',
    s3Sub: 'तय कीजिए कि कितने भोजन छाँटने हैं।',
    nameLabel: 'आपका नाम (केवल इसी उपकरण में संचित)', namePh: 'जैसे वृद्धिम',
    roundLabel: 'कितने भोजन?', roundAll: 'सभी',
    start: 'आरंभ कीजिए', leaderboard: 'उपलब्धि सूची',
    setupHint: 'भोजन को टोकरी में खींचिए, बाएँ या दाएँ सरकाइए, टोकरी छूइए, या 1 दबाकर जैन-अनुकूल और 2 दबाकर जैन-प्रतिकूल बताइए।',
    nameNeeded: 'कृपया पहले अपना नाम लिखिए।',
    binYes: 'जैन-अनुकूल', binYesNote: 'सात्त्विक और अहिंसा-सम्मत',
    binNo: 'जैन-प्रतिकूल', binNoNote: 'जैन आहार में वर्जित',
    binYesArrow: '← खींचिए या 1 दबाइए', binNoArrow: 'खींचिए या 2 दबाइए →',
    cardHint: 'खींचिए, सरकाइए, या टोकरी छूइए',
    hudScore: 'अंक', hudStreak: 'क्रम', hudCount: 'छाँटे',
    verdictYes: 'जैन-अनुकूल है', verdictNo: 'जैन-अनुकूल नहीं है',
    correct: 'शाबाश! बिल्कुल सही।',
    wrong: 'ठीक नहीं — यहाँ पाठ दीजिए।',
    points: '+{n} अंक',
    keepLearning: 'सीखते रहिए',
    next: 'आगे',
    noteLabel: 'पारिवारिक टिप्पणी',
    quit: 'यह बारी छोड़िए',
    quitConfirm: 'यह बारी छोड़ें?', quitBody: 'इस बारी की प्रगति मिट जाएगी।',
    yes: 'हाँ, छोड़ दीजिए', no: 'खेलते रहिए',
    resTitle: ['जिज्ञासु साधक', 'अहिंसा शिक्षु', 'सात्त्विक रसोइया', 'परम सात्त्विक रसोइया'],
    resSub: ['हर बड़ा रसोइया कहीं से ही आरंभ करता है। कुछ भोजन और छाँटिए।',
             'बहुत अच्छा — थोड़ा और अभ्यास, और यह स्वभाव बन जाएगा।',
             'अद्भुत। आपकी रसोई अहिंसा से भरी है।',
             'पूर्ण। आप जैन आहार को भीतर-बाहर जानते हैं।'],
    statScore: 'अंक', statCorrect: 'सही', statBest: 'श्रेष्ठ क्रम', statTime: 'समय',
    rankLine: 'इस उपकरण पर आप #{n} स्थान पर हैं',
    cheers: ['साधु! साधु! अहिंसा रसोई की देहरी से ही आरंभ होती है।',
             'बहुत सुंदर — भोजन में सावधानी ही हर जीव के प्रति सावधानी है।',
             'साधु! हर सही चुनाव एक छोटी सी कोमलता थी।',
             'अद्भुत। सात्त्विक थाली भी एक मौन पूजा है।',
             'साधु! साधु! आपने स्थिर मन से छाँटा।'],
    again: 'पुनः खेलिए', changeSetup: 'सेटिंग बदलिए', showLb: 'उपलब्धि सूची',
    reviewTitle: 'आज आपने क्या सीखा',
    reviewEmpty: 'कोई भूल नहीं हुई — ये चार याद रखिए।',
    lbTitle: 'उपलब्धि सूची · सर्वाधिक अंक', lbClear: 'हटाइए',
    lbEmpty: 'अभी कोई रिकॉर्ड नहीं। पहले खिलाड़ी बनिए!',
    lbConfirmTitle: 'उपलब्धि सूची हटाएँ?',
    lbConfirmBody: 'इस खेल के सभी रिकॉर्ड इस उपकरण से हट जाएँगे।',
    lbCleared: 'रिकॉर्ड हटा दिए गए।',
    thRank: '#', thLbName: 'नाम', thLbLevel: 'स्तर', thLbTime: 'समय', thLbScore: 'अंक',
    storageOff: 'निजी विंडो में रिकॉर्ड संचित नहीं हो सकते — खेल सामान्य रूप से चलता रहेगा।',
    saved: 'बारी संचित हुई · {n} अंक',
    foot: 'अहिंसा के पारंपरिक दिगंबर जैन आहार-सिद्धांतों पर आधारित। आचरण परिवार और परंपरा अनुसार भिन्न हो सकते हैं — अपने बड़ों से अवश्य पूछिए।'
  }
};

