/* ============================================================
   UI DICTIONARY · every visible string lives here
   ============================================================ */
var UI = {
  en: {
    brandHi: 'तीर्थंकर क्रम', brandEn: 'Tirthankar Sorting',
    langSwitch: 'हिंदी', hub: 'All games', restart: 'Restart',
    soundOn: 'Sound on', soundOff: 'Sound off',
    s1Title: 'Choose your language', s1Sub: 'अपनी भाषा चुनिए',
    s3Title: 'Set up your round',
    s3Sub: 'Choose how many Tirthankaras to place, and what you are sorting by.',
    nameLabel: 'Your name (kept on this device only)', namePh: 'e.g. Vraddhim',
    countLabel: 'How many Tirthankaras?',
    modeLabel: 'Sort them by',
    mode: {
      order:  ['Correct order', '1st through 24th'],
      chinh:  ['Emblem', 'Match each lanchan to its name'],
      varna:  ['Complexion', 'Group by traditional colour'],
      moksha: ['Nirvana place', 'Group by where each attained moksha']
    },
    diffLabel: 'Difficulty',
    diff: { hard: ['Hard · no hints', 'Easy · show position numbers'], easy: ['Easy · show position numbers', 'Hard · no hints'] },
    start: 'Begin', leaderboard: 'Leaderboard',
    setupHint: 'Drag a tile, or tap one tile then another to swap. Arrow keys move a tile, Enter drops it.',
    nameNeeded: 'Please write your name first.',
    modeNeeds8: 'The nirvana-place round needs at least 8 Tirthankaras, so every place can appear.',
    hudPlaced: 'Placed', hudMoves: 'Moves', hudTime: 'Time', hudHints: 'Hints',
    playHintOrder: 'Arrange them from the 1st Tirthankara to the last.',
    playHintChinh: 'Drop each emblem under the name it belongs to.',
    playHintBucket: 'Tap a tile, then tap the group it belongs to.',
    hint: 'Hint', hintsLeft: '{n} left',
    hintUsed: 'A correct tile is glowing. {n} hints left, {s}s added.',
    hintNone: 'No hints left — finish from memory.',
    quit: 'Leave this round',
    quitConfirm: 'Leave this round?', quitBody: 'Your progress in this round will be lost.',
    yes: 'Yes, leave', no: 'Keep playing',
    incomplete: 'Some tiles are not in place yet. Keep going.',
    resTitle: ['A quiet beginning', 'Well arranged', 'Strong recall', 'Sadhu! Sadhu!'],
    resSub: ['Every great journey starts with one step. Try a smaller round.',
             'You are learning them well. Try more tiles next.',
             'Very good. The order is settling into memory.',
             'Perfectly placed, and quickly.'],
    statTime: 'Time', statMoves: 'Moves', statHints: 'Hints', statTiles: 'Tiles',
    rankLine: 'You are #{n} on this device',
    cheers: ['Sadhu! Sadhu! A steady mind remembers well.',
             'Well done — patience is its own form of tap.',
             'Sadhu! Each name you placed is a step closer to the path.',
             'Beautiful. Remembering them is itself a small worship.',
             'Sadhu! Sadhu! Your attention did not wander.'],
    again: 'Play again', changeSetup: 'Change set-up', showLb: 'Leaderboard',
    reviewTitle: 'The 24 Tirthankaras',
    thNo: '#', thName: 'Tirthankara', thChinh: 'Emblem', thVarna: 'Colour',
    thAasan: 'Posture', thMoksha: 'Nirvana place', thJanma: 'Birth place',
    tradTitle: 'Tradition notes',
    lbTitle: 'Leaderboard · fastest rounds', lbClear: 'Clear',
    lbEmpty: 'No records yet. Be the first!',
    lbConfirmTitle: 'Clear the leaderboard?',
    lbConfirmBody: 'Every record for this game will be removed from this device.',
    lbCleared: 'Records cleared.',
    thRank: '#', thLbName: 'Name', thLbLevel: 'Level', thLbTime: 'Time', thLbMoves: 'Moves',
    storageOff: 'Records cannot be saved in a private window — the game still plays.',
    saved: 'Round saved · {time}',
    selected: 'Selected {name}. Now choose where it goes.',
    swapped: 'Moved {name}.',
    placedIn: '{name} placed in {bucket}.',
    foot: 'Rooted in the Digambar Jain tradition. Emblem and place conventions vary by family and lineage — always ask your elders.'
  },
  hi: {
    brandHi: 'तीर्थंकर क्रम', brandEn: 'Tirthankar Sorting',
    langSwitch: 'English', hub: 'सभी खेल', restart: 'पुनः आरंभ',
    soundOn: 'ध्वनि चालू', soundOff: 'ध्वनि बंद',
    s1Title: 'अपनी भाषा चुनिए', s1Sub: 'Choose your language',
    s3Title: 'अपनी बारी सजाइए',
    s3Sub: 'तय कीजिए कि कितने तीर्थंकर रखने हैं और किस आधार पर क्रम बनाना है।',
    nameLabel: 'आपका नाम (केवल इसी उपकरण में संचित)', namePh: 'जैसे वृद्धिम',
    countLabel: 'कितने तीर्थंकर?',
    modeLabel: 'किस आधार पर छाँटिए',
    mode: {
      order:  ['सही क्रम', 'प्रथम से चौबीसवें तक'],
      chinh:  ['चिन्ह', 'प्रत्येक लांछन को उसके नाम से मिलाइए'],
      varna:  ['वर्ण', 'परंपरागत रंग के अनुसार समूह बनाइए'],
      moksha: ['निर्वाण स्थल', 'मोक्ष स्थान के अनुसार समूह बनाइए']
    },
    diffLabel: 'कठिनाई',
    diff: { hard: ['कठिन · कोई संकेत नहीं', 'सरल · स्थान संख्या दिखाएँ'], easy: ['सरल · स्थान संख्या दिखाएँ', 'कठिन · कोई संकेत नहीं'] },
    start: 'आरंभ कीजिए', leaderboard: 'उपलब्धि सूची',
    setupHint: 'टाइल खींचिए, या एक टाइल छूकर दूसरी छूइए — अदला-बदली हो जाएगी। तीर कुंजी से चलिए, Enter से रखिए।',
    nameNeeded: 'कृपया पहले अपना नाम लिखिए।',
    modeNeeds8: 'निर्वाण स्थल वाली बारी हेतु कम से कम 8 तीर्थंकर चाहिए, ताकि सभी स्थान आ सकें।',
    hudPlaced: 'सही स्थान', hudMoves: 'चालें', hudTime: 'समय', hudHints: 'संकेत',
    playHintOrder: 'इन्हें प्रथम से अंतिम तीर्थंकर के क्रम में लगाइए।',
    playHintChinh: 'प्रत्येक चिन्ह को उसके नाम के नीचे रखिए।',
    playHintBucket: 'पहले टाइल छूइए, फिर उसका समूह छूइए।',
    hint: 'संकेत', hintsLeft: '{n} शेष',
    hintUsed: 'एक सही टाइल चमक रही है। {n} संकेत शेष, {s} सेकंड जुड़े।',
    hintNone: 'संकेत समाप्त — अब स्मृति से पूरा कीजिए।',
    quit: 'यह बारी छोड़िए',
    quitConfirm: 'यह बारी छोड़ें?', quitBody: 'इस बारी की प्रगति मिट जाएगी।',
    yes: 'हाँ, छोड़ दीजिए', no: 'खेलते रहिए',
    incomplete: 'कुछ टाइल अभी सही स्थान पर नहीं हैं। प्रयास जारी रखिए।',
    resTitle: ['शांत आरंभ', 'अच्छा क्रम', 'दृढ़ स्मृति', 'साधु! साधु!'],
    resSub: ['हर बड़ी यात्रा एक कदम से शुरू होती है। छोटी बारी लीजिए।',
             'आप इन्हें अच्छे से सीख रहे हैं। अगली बार अधिक टाइल लीजिए।',
             'बहुत अच्छा। क्रम अब स्मृति में बैठने लगा है।',
             'पूर्णतः सही और तेज़ भी।'],
    statTime: 'समय', statMoves: 'चालें', statHints: 'संकेत', statTiles: 'टाइलें',
    rankLine: 'इस उपकरण पर आप #{n} स्थान पर हैं',
    cheers: ['साधु! साधु! स्थिर मन ही अच्छा स्मरण करता है।',
             'बहुत सुंदर — धैर्य भी एक तप है।',
             'साधु! हर रखा गया नाम पथ की ओर एक कदम है।',
             'अद्भुत। इन्हें याद रखना भी एक छोटी पूजा है।',
             'साधु! साधु! आपका ध्यान कहीं भटका नहीं।'],
    again: 'पुनः खेलिए', changeSetup: 'सेटिंग बदलिए', showLb: 'उपलब्धि सूची',
    reviewTitle: 'चौबीस तीर्थंकर',
    thNo: '#', thName: 'तीर्थंकर', thChinh: 'चिन्ह', thVarna: 'वर्ण',
    thAasan: 'आसन', thMoksha: 'निर्वाण स्थल', thJanma: 'जन्म स्थल',
    tradTitle: 'परंपरा भेद',
    lbTitle: 'उपलब्धि सूची · सबसे तेज़ बारी', lbClear: 'हटाइए',
    lbEmpty: 'अभी कोई रिकॉर्ड नहीं। पहले खिलाड़ी बनिए!',
    lbConfirmTitle: 'उपलब्धि सूची हटाएँ?',
    lbConfirmBody: 'इस खेल के सभी रिकॉर्ड इस उपकरण से हट जाएँगे।',
    lbCleared: 'रिकॉर्ड हटा दिए गए।',
    thRank: '#', thLbName: 'नाम', thLbLevel: 'स्तर', thLbTime: 'समय', thLbMoves: 'चालें',
    storageOff: 'निजी विंडो में रिकॉर्ड संचित नहीं हो सकते — खेल सामान्य रूप से चलता रहेगा।',
    saved: 'बारी संचित हुई · {time}',
    selected: '{name} चुना। अब बताइए यह कहाँ जाए।',
    swapped: '{name} खिसका।',
    placedIn: '{name} · {bucket} में रखा।',
    foot: 'दिगंबर जैन परंपरा से प्रेरित। चिन्ह और स्थल की परंपराएँ परिवार अनुसार भिन्न हो सकती हैं — अपने बड़ों से अवश्य पूछिए।'
  }
};

