/* Identity + rules for Myth Busters. */
var GAME_ID = 'myth-busters';
var LB_KEY = 'jinbhakt:kids:leaderboard:v1';
var PREF_KEY = 'jinbhakt:kids:prefs:v1';
var LB_MAX = 20;

/** Higher score wins; more correct answers breaks a tie. */
var LB_CMP = function (a, b) {
  return (b.score - a.score) ||
         (((b.meta && b.meta.correct) || 0) - ((a.meta && a.meta.correct) || 0)) ||
         (a.duration - b.duration) ||
         (b.ts - a.ts);
};

var ROUNDS = [10, 20, 0];                 // 0 === "all"
var TIMERS = [                              // seconds per statement, 0 = none
  { key: 'relaxed',  sec: 20 },
  { key: 'standard', sec: 12 },
  { key: 'quick',    sec: 8 },
  { key: 'none',     sec: 0 }
];
var BASE = 10, STREAK_BONUS = 5, STREAK_AT = 3;
var WARN_AT = 0.4;                        // timer bar turns amber at 40% left

var TOPICS = [
  ['tirthankara', 'Tirthankaras', 'तीर्थंकर'],
  ['ahimsa',      'Ahimsa & food', 'अहिंसा और आहार'],
  ['doctrine',    'Anekant · Ratnatraya · Karma', 'अनेकान्त · रत्नत्रय · कर्म'],
  ['monastic',    'Monks, nuns & vows', 'मुनि-साध्वी और व्रत'],
  ['symbol',      'Symbols & mantras', 'प्रतीक और मंत्र'],
  ['festival',    'Festivals & calendar', 'पर्व और संवत्'],
  ['scripture',   'Scriptures & Acharyas', 'ग्रन्थ और आचार्य'],
  ['digambar',    'Digambar tradition', 'दिगंबर परंपरा']
];

/* Row: [id, aud('kids'|'adults'|'both'), topic, answer(1=true,0=false),
         enStatement, hiStatement, enCorrection, hiCorrection] */
var QUESTIONS = [
['m01','both','tirthankara',0,'Lord Mahavira founded Jainism.','भगवान महावीर ने जैन धर्म की स्थापना की।','Mahavira was the 24th and last Tirthankara — a teacher who revived an ancient path. Jains hold the tradition to be beginningless, with Rishabhdev as the first Tirthankara of this cycle.','महावीर स्वामी चौबीसवें और अंतिम तीर्थंकर थे — एक प्राचीन पथ को पुनः प्रकाशित करने वाले शिक्षक। जैन परंपरा को अनादि मानते हैं, और इस कालखंड के प्रथम तीर्थंकर ऋषभदेव हैं।'],
['m02','both','tirthankara',1,'There are 24 Tirthankaras in the present cycle.','वर्तमान कालखंड में चौबीस तीर्थंकर हुए हैं।','Correct. From Rishabhdev to Mahavira, each Tirthankara re-established the same path of non-violence, truth and restraint.','सही। ऋषभदेव से महावीर तक, प्रत्येक तीर्थंकर ने अहिंसा, सत्य और संयम का एक ही मार्ग पुनः स्थापित किया।'],
['m03','kids','tirthankara',1,'The first Tirthankara is called Rishabhdev.','प्रथम तीर्थंकर ऋषभदेव कहलाते हैं।','Yes. Rishabhdev is also honoured as Adinatha, the first lord, and his emblem is the bull.','जी। ऋषभदेव को आदिनाथ भी कहा जाता है, और उनका लांछन वृषभ है।'],
['m04','kids','tirthankara',0,'Lord Mahavira’s emblem is the elephant.','भगवान महावीर का चिन्ह हाथी है।','Mahavira’s emblem is the lion. The elephant belongs to the second Tirthankara, Ajitanatha.','महावीर का लांछन सिंह है। हाथी दूसरे तीर्थंकर अजितनाथ का चिन्ह है।'],
['m05','adults','tirthankara',0,'All 24 Tirthankaras attained moksha at Sammed Shikharji.','सभी चौबीस तीर्थंकरों को सम्मेद शिखरजी पर मोक्ष प्राप्त हुआ।','Twenty of them did. Rishabhdev attained moksha at Ashtapada, Vasupujya at Champapuri, Neminatha at Girnar and Mahavira at Pavapuri.','बीस को वहाँ मोक्ष मिला। ऋषभदेव को अष्टापद, वासुपूज्य को चम्पापुरी, नेमिनाथ को गिरनार और महावीर को पावापुरी में।'],
['m06','adults','tirthankara',1,'Only three Tirthankaras are traditionally shown seated in padmasana.','परंपरा में केवल तीन तीर्थंकर पद्मासन में बैठे दिखाए जाते हैं।','Correct — Rishabhdev, Neminatha and Mahavira. The other twenty-one are shown standing in kayotsarga.','सही — ऋषभदेव, नेमिनाथ और महावीर। शेष इक्कीस कायोत्सर्ग में खड़े दिखाए जाते हैं।'],
['m07','both','tirthankara',0,'Tirthankaras grant boons to those who pray to them.','तीर्थंकर प्रार्थना करने वालों को वरदान देते हैं।','A Tirthankara is a liberated soul beyond the universe, free of all attachment. Jains venerate them to absorb their qualities, not to ask for favours.','तीर्थंकर विश्व के पार मुक्त आत्मा हैं, सब आसक्ति से रहित। जैन उनके गुण ग्रहण करने हेतु उनकी वंदना करते हैं, वरदान माँगने हेतु नहीं।'],
['m08','kids','tirthankara',1,'Parshvanatha’s emblem is the serpent.','पार्श्वनाथ का चिन्ह सर्प है।','Yes. He is shown with a serpent hood above him, and his complexion is blue.','जी। उनके ऊपर फण दिखाया जाता है, और उनका वर्ण नील है।'],
['m09','adults','tirthankara',1,'The 7th Tirthankara Suparshvanatha bears the swastika as his emblem.','सातवें तीर्थंकर सुपार्श्वनाथ का लांछन स्वस्तिक है।','Correct. The swastika is an ancient Jain auspicious mark, long predating any other use of that shape.','सही। स्वस्तिक एक प्राचीन जैन मंगल-चिन्ह है, जो इस आकृति के किसी भी अन्य प्रयोग से बहुत पूर्व का है।'],
['m10','kids','tirthankara',0,'Mahavira was born in Pavapuri.','महावीर का जन्म पावापुरी में हुआ था।','He was born at Kundagrama, near Vaishali. Pavapuri is where he attained nirvana.','उनका जन्म कुण्डग्राम में, वैशाली के समीप हुआ। पावापुरी वे स्थान है जहाँ उन्हें निर्वाण प्राप्त हुआ।'],
['m11','adults','tirthankara',1,'Neminatha is also known as Arishtanemi.','नेमिनाथ को अरिष्टनेमि भी कहा जाता है।','Correct. He is the 22nd Tirthankara, his emblem is the conch, and he attained moksha at Girnar.','सही। वे बाईसवें तीर्थंकर हैं, उनका लांछन शंख है, और उन्हें गिरनार पर मोक्ष प्राप्त हुआ।'],
['m12','kids','tirthankara',1,'Mallinatha’s emblem is the water pot.','मल्लिनाथ का चिन्ह कलश है।','Yes. In the Digambar tradition Mallinatha is shown with a kalash and a blue complexion.','जी। दिगंबर परंपरा में मल्लिनाथ कलश के साथ और नील वर्ण में दिखाए जाते हैं।'],
['m13','both','ahimsa',1,'Ahimsa Paramo Dharmah means non-violence is the supreme duty.','अहिंसा परमो धर्मः का अर्थ है — अहिंसा ही परम धर्म है।','Correct. Ahimsa in thought, word and deed toward every being, great and tiny, is the highest principle in Jainism.','सही। मन, वचन और काया से हर जीव के प्रति — बड़े हो या सूक्ष्म — अहिंसा ही जैन धर्म का परम सिद्धांत है।'],
['m14','both','ahimsa',1,'Jains avoid root vegetables because uprooting kills the whole plant.','जैन कंद-मूल सब्ज़ियाँ इसलिए त्यागते हैं क्योंकि उखाड़ने से पूरा पौधा मर जाता है।','Yes. Pulling a root ends the plant’s whole life and disturbs countless tiny beings living in that soil.','जी। जड़ खींचने से पौधे का पूरा जीवन समाप्त होता है और उस मिट्टी में बसे असंख्य सूक्ष्म जीव हिलते हैं।'],
['m15','kids','ahimsa',0,'Honey is fine because bees make too much of it anyway.','शहद ठीक है क्योंकि मधुमक्खियाँ वैसे भी अधिक बना लेती हैं।','Bees labour for every drop, and taking it harms the hive. That is why honey is given up entirely.','हर बूँद के लिए मधुमक्खियाँ श्रम करती हैं, और इसे लेने से छत्ते को हानि होती है। इसीलिए शहद पूर्णतः त्याग किया जाता है।'],
['m16','both','ahimsa',1,'Jains believe every living being, even the smallest, has a soul.','जैन मानते हैं कि हर जीव — सबसे सूक्ष्म भी — आत्मा रखता है।','Correct. From elephants to micro-organisms, every jiva has a soul of infinite potential. That belief is the root of Jain care for all life.','सही। हाथी से लेकर सूक्ष्मजीव तक, हर जीव की आत्मा अनंत सामर्थ्य वाली है। यही मान्यता सभी जीवन के प्रति जैन सावधानी का मूल है।'],
['m17','adults','ahimsa',0,'Anantkāy foods are avoided only because they taste strong.','अनंतकाय भोजन केवल तीखे स्वाद के कारण त्यागे जाते हैं।','Anantkāy means one body housing countless lives. Figs and banyan fruit are set aside to avoid that harm, not because of taste.','अनंतकाय का अर्थ है एक ही शरीर में असंख्य जीवन। अंजीर और बरगदी इस हानि से बचने हेतु त्यागे जाते हैं, स्वाद के कारण नहीं।'],
['m18','adults','ahimsa',1,'Jain kitchens usually close before sunset.','जैन रसोई सामान्यतः सूर्यास्त से पूर्व बंद हो जाती है।','Correct. Tiny beings gather near light, water and food after dark, so food is cooked and eaten in daylight.','सही। अँधेरे के पश्चात सूक्ष्म जीव प्रकाश, जल और भोजन के पास एकत्र होते हैं, अतः भोजन दिन के प्रकाश में बनता और खाया जाता है।'],
['m19','kids','ahimsa',1,'Eating above-ground food harms fewer living beings.','ज़मीन के ऊपर का भोजन खाने से कम जीवों को हानि पहुँचती है।','Yes. Grains, pulses, nuts and most fruits are harvested without ending the plant’s life.','जी। अन्न, दाल, मेवा और अधिकांश फल पौधे का जीवन समाप्त किए बिना एकत्र होते हैं।'],
['m20','adults','ahimsa',0,'Jainism permits eating fish in coastal regions.','जैन धर्म तटीय क्षेत्रों में मछली खाने की अनुमति देता है।','Ahimsa admits no exception of place. Flesh of any kind, from any region, is wholly outside a Jain diet.','अहिंसा में स्थान का कोई अपवाद नहीं। किसी भी क्षेत्र का, किसी भी प्रकार का मांस जैन आहार से पूर्णतः बाहर है।'],
['m21','kids','ahimsa',1,'Jain monks gently clear the path before they walk.','जैन मुनि चलने से पूर्व मार्ग को धीरे से साफ़ करते हैं।','Yes. A soft broom is used to move insects out of harm’s way so no creature is crushed underfoot.','जी। कोमल बुहारी से कीटों को हटाया जाता है ताकि कोई भी जीव पैर के नीचे न कुचला जाए।'],
['m22','adults','ahimsa',1,'Milk is accepted in the Jain diet.','दूध जैन आहार में स्वीकार्य है।','Correct. Dairy taken without harming the animal is traditionally accepted, though many families keep strict rules about when and how it is used.','सही। पशु को हानि पहुँचाए बिना लिया गया दुग्ध उत्पाद परंपरा में स्वीकार्य है, तथापि अनेक परिवार इसके समय और विधि पर कड़े नियम रखते हैं।'],
['m23','both','doctrine',0,'Jains believe a Creator God made the universe.','जैन मानते हैं कि ईश्वर ने विश्व की रचना की।','Jainism teaches the universe is uncreated and eternal, running on its own natural laws. Liberated souls are revered, but there is no creator.','जैन सिद्धांत में लोक अनादि और नित्य है, जो अपने स्वाभाविक नियमों से चलता है। मुक्त आत्माओं की वंदना होती है, पर कोई कर्ता-निर्माता नहीं है।'],
['m24','both','doctrine',0,'Anekantavada means there is only one correct way to see anything.','अनेकान्तवाद का अर्थ है कि किसी भी वस्तु को देखने का केवल एक ही सही मार्ग है।','It means the opposite — truth has many valid sides, like the blind men and the elephant. It teaches intellectual humility.','इसका अर्थ ठीक विपरीत है — सत्य के अनेक वैध पक्ष होते हैं, जैसे अंधों और हाथी की कथा। यह बौद्धिक नम्रता सिखाता है।'],
['m25','both','doctrine',1,'The Ratnatraya are Right Faith, Right Knowledge and Right Conduct.','रत्नत्रय हैं — सम्यक् दर्शन, सम्यक् ज्ञान और सम्यक् चारित्र।','Correct. These three jewels together form the Jain path to liberation; none of them works alone.','सही। ये तीनों रत्न मिलकर मोक्ष का मार्ग बनाते हैं; इनमें से कोई भी अकेले सिद्ध नहीं होता।'],
['m26','adults','doctrine',1,'In Jainism karma is described as subtle matter that clings to the soul.','जैन धर्म में कर्म को सूक्ष्म पुद्गल बताया गया है जो आत्मा से चिपकता है।','Yes. Karma is understood as karmic particles that bind to the soul through passion and action, like dust settling on wet cloth.','जी। कर्म को कर्मण-पुद्गल माना जाता है जो कषाय और क्रिया से आत्मा से बँधते हैं, जैसे गीले वस्त्र पर धूल।'],
['m27','kids','doctrine',1,'The soul never dies; it takes a new body.','आत्मा कभी नहीं मरती; वह नया शरीर लेती है।','Correct. The soul is eternal and moves through rebirth, shaped by its karma, until it is liberated.','सही। आत्मा नित्य है और कर्मों के अनुसार पुनर्जन्म से गुज़रती है, जब तक वह मुक्त नहीं हो जाती।'],
['m28','adults','doctrine',0,'Liberation in Jainism means merging into God.','जैन धर्म में मोक्ष का अर्थ है ईश्वर में विलीन हो जाना।','Moksha means the soul rises to Siddhashila at the summit of the universe, alone in its own infinite knowledge and bliss — not merged into anything.','मोक्ष में आत्मा लोक के शिखर पर सिद्धशिला को प्राप्त होती है, अपने अनंत ज्ञान और आनंद में स्वतंत्र — किसी में विलीन नहीं होती।'],
['m29','kids','doctrine',1,'Parasparopagraho Jivanam means souls help one another.','परस्परोपग्रहो जीवानाम् का अर्थ है — जीव एक-दूसरे की सहायता करते हैं।','Yes. This line from the Tattvartha Sutra is the Jain motto: all life is interconnected.','जी। तत्त्वार्थसूत्र का यह वाक्य ही जैन का आदर्श वाक्य है — समस्त जीवन परस्पर जुड़ा हुआ है।'],
['m30','adults','doctrine',0,'Only human beings can attain moksha.','केवल मनुष्य ही मोक्ष प्राप्त कर सकते हैं।','Any soul capable of right faith, knowledge and conduct may rise to liberation; the potential is infinite in every jiva.','सम्यक् दर्शन, ज्ञान और चारित्र का सामर्थ्य रखने वाली कोई भी आत्मा मोक्ष को प्राप्त कर सकती है; हर जीव में यह सामर्थ्य अनंत है।'],
['m31','both','doctrine',1,'The five great vows include truthfulness and non-stealing.','पाँच महाव्रतों में सत्य और अस्तेय भी शामिल हैं।','Correct. They are ahimsa, satya, achaurya, brahmacharya and aparigraha — non-violence, truth, non-stealing, celibacy and non-possession.','सही। वे हैं अहिंसा, सत्य, अस्तेय, ब्रह्मचर्य और अपरिग्रह।'],
['m32','adults','doctrine',1,'Aparigraha means non-possession.','अपरिग्रह का अर्थ है परिग्रह-त्याग।','Correct. It covers outer possessions and inner attachment to them both; monks live it fully, householders in measure.','सही। इसमें बाहरी संपत्ति और उसके भीतर का मोह दोनों आते हैं; मुनि इसे पूर्णतः और श्रावक परिमित रूप में साधते हैं।'],
['m33','adults','doctrine',0,'Syadvada is a doctrine of doubt and uncertainty.','स्याद्वाद संदेह और अनिश्चय का सिद्धांत है।','Syadvada is the careful method of holding that every judgement is true from some standpoint. It refines certainty; it does not abandon it.','स्याद्वाद वह सतर्क पद्धति है जो मानती है कि हर निर्णय किसी न किसी नय से सत्य है। यह निश्चय को परिष्कृत करता है, त्यागता नहीं।'],
['m34','both','doctrine',1,'Karma can be shed as well as bound.','कर्म का बंधन और निर्जरा दोनों होती है।','Correct. Bandha binds karma through passion; samvara stops the inflow and nirjara burns off what is already gathered.','सही। कषाय से कर्म का बंध होता है; संवर से आगमन रुकता है और निर्जरा से संचित कर्म क्षीण होते हैं।'],
['m35','both','monastic',0,'Digambara monks wear bright saffron robes.','दिगंबर मुनि गहरे केसरिया वस्त्र धारण करते हैं।','Digambara means sky-clad. A Digambara monk owns nothing, not even cloth, as the ultimate practice of aparigraha. It is Shvetambara monks who wear simple white robes.','दिगंबर का अर्थ है आकाश-वस्त्र। दिगंबर मुनि कुछ भी परिग्रह नहीं रखते, वस्त्र भी नहीं — यही अपरिग्रह की परम साधना है। श्वेतांबर मुनि सादे श्वेत वस्त्र धारण करते हैं।'],
['m36','both','monastic',1,'Jain monks and nuns own almost nothing.','जैन मुनि और साध्वियाँ लगभग कुछ भी परिग्रह नहीं रखते।','Correct. Their possessions are limited to the bare essential, and many accept food only as alms.','सही। उनका परिग्रह केवल नितावश्यक वस्तुओं तक सीमित है, और अनेक केवल भिक्षा ही ग्रहण करते हैं।'],
['m37','adults','monastic',1,'Householders observe twelve vows in all.','श्रावक कुल बारह व्रतों का पालन करते हैं।','Correct. The five anuvratas, three gunavratas and four shikshavratas together form the twelve vows of a householder.','सही। पाँच अणुव्रत, तीन गुणव्रत और चार शिक्षाव्रत मिलकर श्रावक के बारह व्रत बनते हैं।'],
['m38','kids','monastic',0,'Jain monks travel everywhere by car.','जैन मुनि हर स्थान पर कार से यात्रा करते हैं।','Monks and nuns walk, and they walk carefully. A vehicle would risk harm to beings along the way.','मुनि और साध्वियाँ पैदल चलते हैं, और अति सावधानी से। वाहन से मार्ग में जीवों को हानि का भय रहता है।'],
['m39','adults','monastic',1,'Pratikramana is a ritual of reflection and seeking forgiveness.','प्रतिक्रमण आलोचना और क्षमा-याचना की विधि है।','Correct. It is performed at set times to review one’s conduct, repent for lapses and ask forgiveness of all beings.','सही। इसे नियत काल में किया जाता है — अपने आचरण की समीक्षा, भूल पर पश्चात्ताप और सभी जीवों से क्षमा-प्रार्थना।'],
['m40','kids','monastic',1,'Micchami Dukkadam is a way of asking forgiveness.','मिच्छामि दुक्कड़म् क्षमा माँगने का भाव है।','Yes. It means may all my wrong actions bear no fruit — spoken especially on Samvatsari and Kshamavani.','जी। इसका भाव है कि मेरे सभी दुष्कर्म निष्फल हो जाएँ — विशेषतः संवत्सरी और क्षमावाणी पर कहा जाता है।'],
['m41','adults','monastic',0,'Jain nuns hold a higher rank than monks.','जैन साध्वियों का स्थान मुनियों से ऊँचा है।','Rank follows conduct and seniority, not gender. The path of restraint is equally open to every soul.','स्थान आचरण और ज्येष्ठता से निर्धारित होता है, लिंग से नहीं। संयम का मार्ग हर आत्मा के लिए समान रूप से खुला है।'],
['m42','both','monastic',1,'Samayika is a practice of sitting in equanimity.','सामायिक समभाव में बैठने की साधना है।','Correct. For a fixed period one withdraws from activity and rests the mind in evenness toward all beings.','सही। नियत काल तक क्रियाओं से हटकर मन को सभी जीवों के प्रति समभाव में स्थिर किया जाता है।'],
['m43','adults','monastic',1,'Monks accept food only within set daylight hours.','मुनि केवल नियत दिन-काल में ही भोजन ग्रहण करते हैं।','Correct. Alms are taken once, before sunset, from households that prepared the food with care.','सही। भिक्षा एक बार, सूर्यास्त से पूर्व, उन घरों से ली जाती है जिन्होंने भोजन सावधानी से बनाया हो।'],
['m44','both','symbol',0,'The Jain emblem shows a hand holding a sword.','जैन प्रतीक में तलवार थामे हाथ दिखाया गया है।','The raised palm means stop, do no harm. The wheel in the palm is the cycle of birth and rebirth that ahimsa helps us leave.','ऊपर उठा हुआ हाथ कहता है — रुकिए, किसी को हानि न पहुँचाइए। हथेली का चक्र जन्म-मरण का वह चक्र है जिसे अहिंसा छोड़ने में सहायता करती है।'],
['m45','both','symbol',1,'The raised palm on the Jain emblem means stop and do no harm.','जैन प्रतीक का ऊपर उठा हाथ कहता है — रुकिए और हानि मत कीजिए।','Correct. It asks the viewer to pause and consider before any action that could injure a living being.','सही। यह दर्शक से कहता है कि किसी भी जीव को हानि पहुँचाने वाली क्रिया से पूर्व रुकें और विचार करें।'],
['m46','adults','symbol',0,'The Namokar Mantra asks God for wishes and boons.','णमोकार मंत्र ईश्वर से मनोकामना और वरदान माँगता है।','The Navkar Mantra asks for nothing. It simply bows to the virtues of the five supreme beings so that we may become like them.','णमोकार मंत्र कुछ भी नहीं माँगता। वह केवल पंच परमेष्ठी के गुणों को नमन करता है, ताकि हम भी उन जैसे बन सकें।'],
['m47','kids','symbol',1,'The Namokar Mantra bows to five kinds of great souls.','णमोकार मंत्र पाँच प्रकार की महान आत्माओं को नमन करता है।','Yes — Arihanta, Siddha, Acharya, Upadhyaya and Sadhu. These five are the Panch Parmeshthi.','जी — अरिहंत, सिद्ध, आचार्य, उपाध्याय और साधु। इन्हीं पाँच को पंच परमेष्ठी कहा जाता है।'],
['m48','adults','symbol',1,'The Jain swastika’s four arms recall the four states of existence.','जैन स्वस्तिक की चार भुजाएँ चार गतियों का बोध कराती हैं।','Correct. They point to the four destinations — heavenly, human, animal and infernal — through which a soul may pass.','सही। वे चार गतियों का स्मरण कराती हैं — देव, मनुष्य, तिर्यंच और नारक — जिनसे आत्मा गुज़र सकती है।'],
['m49','kids','symbol',1,'The swastika is an ancient auspicious mark in Jainism.','स्वस्तिक जैन धर्म में एक प्राचीन मंगल-चिन्ह है।','Yes. It is the emblem of the seventh Tirthankara and is used in worship and in drawing ritual diagrams.','जी। यह सातवें तीर्थंकर का लांछन है और पूजा तथा मंडल-रचना में प्रयुक्त होता है।'],
['m50','adults','symbol',0,'The three dots above the Jain swastika represent three Gods.','जैन स्वस्तिक के ऊपर के तीन बिंदु तीन देवताओं को दर्शाते हैं।','They stand for the three jewels — right faith, right knowledge and right conduct — not for three deities.','वे तीन रत्नों का बोध कराते हैं — सम्यक् दर्शन, सम्यक् ज्ञान और सम्यक् चारित्र — तीन देवताओं का नहीं।'],
['m51','both','symbol',1,'The outline of the Jain emblem represents the shape of the universe.','जैन प्रतीक की बाहरी रेखा लोक के आकार को दर्शाती है।','Correct. It shows the loka as narrow at the top, wide in the middle and broad at the base.','सही। यह लोक को ऊपर संकीर्ण, मध्य में विस्तृत और आधार पर चौड़ा दिखाती है।'],
['m52','kids','symbol',1,'Hreem is a sacred syllable used in Jain worship.','ह्रीं जैन पूजा में प्रयुक्त एक पवित्र बीजाक्षर है।','Yes. It is a bija mantra held in great reverence, written on ritual diagrams and manuscripts.','जी। यह अति आदरणीय बीज मंत्र है, जिसे मंडल और ग्रंथों पर लिखा जाता है।'],
['m53','both','festival',1,'Jains celebrate Diwali because Lord Mahavira attained nirvana that day.','जैन दीपावली इसलिए मनाते हैं क्योंकि उस दिन भगवान महावीर को निर्वाण प्राप्त हुआ।','Yes. For Jains Diwali marks Mahavira’s liberation at Pavapuri, and the next day begins the Jain New Year, Veer Samvat.','जी। जैनों हेतु दीपावली पावापुरी में महावीर के मोक्ष का स्मरण है, और अगले दिन से जैन नववर्ष वीर संवत् आरंभ होता है।'],
['m54','adults','festival',1,'Paryushana is a period of fasting, study and forgiveness.','पर्युषण उपवास, स्वाध्याय और क्षमा का काल है।','Correct. It is the holiest period of the Jain year, ending with Samvatsari, when forgiveness is asked of everyone.','सही। यह जैन वर्ष का सबसे पवित्र काल है, जिसका समापन संवत्सरी पर होता है, जब सभी से क्षमा माँगी जाती है।'],
['m55','kids','festival',0,'Mahavir Jayanti celebrates Mahavira’s nirvana.','महावीर जयंती महावीर के निर्वाण का उत्सव है।','It celebrates his birth. His nirvana is remembered on Diwali.','यह उनके जन्म का उत्सव है। उनके निर्वाण का स्मरण दीपावली पर किया जाता है।'],
['m56','adults','festival',1,'Akshaya Tritiya remembers Rishabhdev ending his year-long fast.','अक्षय तृतीया ऋषभदेव के वर्ष-व्यापी उपवास के समापन का स्मरण है।','Correct. He broke the fast with sugarcane juice offered by his son Bharata.','सही। उनके पुत्र भरत द्वारा दिए गए ईख के रस से उन्होंने उपवास तोड़ा।'],
['m57','both','festival',1,'Kshamavani is the day set aside for asking forgiveness.','क्षमावाणी क्षमा माँगने हेतु नियत दिवस है।','Yes. On this day Jains seek forgiveness from everyone they may have hurt, knowingly or unknowingly.','जी। इस दिन जैन सभी से क्षमा माँगते हैं, जिनें उन्होंने जानते-अनजाने में कष्ट पहुँचाया हो।'],
['m58','adults','festival',0,'Jain festivals are chiefly occasions for feasting.','जैन पर्व मुख्यतः भोज-उत्सव के अवसर हैं।','They are occasions for restraint, study and charity. Fasting and simplicity mark them far more than feasting.','वे संयम, स्वाध्याय और दान के अवसर हैं। इनमें उपवास और सादगी का स्थान भोज से कहीं अधिक है।'],
['m59','kids','festival',1,'Shrut Panchami honours sacred knowledge.','श्रुत पंचमी ज्ञान का सम्मान करती है।','Yes. On this day scriptures and teachers are honoured, and manuscripts are reverently cleaned and worshipped.','जी। इस दिन ग्रंथों और गुरुओं का सम्मान होता है, तथा पाण्डुलिपियों को आदरपूर्वक शुद्ध कर पूजा जाता है।'],
['m60','adults','festival',1,'The Jain New Year begins the day after Diwali.','जैन नववर्ष दीपावली के अगले दिन आरंभ होता है।','Correct. It is called Veer Samvat, counted from the year of Mahavira’s nirvana.','सही। इसे वीर संवत् कहते हैं, जो महावीर के निर्वाण वर्ष से गिना जाता है।'],
['m61','both','scripture',1,'Kundakunda, author of the Samayasara, was a great Digambara Acharya.','समयसार के रचयिता कुन्दकुन्द एक महान दिगंबर आचार्य थे।','Correct. His works, among them the Samayasara and the Pravachanasara, are among the most revered in Digambar philosophy.','सही। समयसार और प्रवचनसार सहित उनकी रचनाएँ दिगंबर दर्शन में सर्वोच्च आदरणीय मानी जाती हैं।'],
['m62','both','scripture',1,'The Tattvartha Sutra is accepted by both major Jain traditions.','तत्त्वार्थसूत्र दोनों प्रमुख जैन परंपराओं में स्वीकार्य है।','Correct. Written by Acharya Umasvati, it is the rare text both Digambaras and Shvetambaras hold as authoritative.','सही। आचार्य उमास्वाति की इस रचना को दिगंबर और श्वेतांबर दोनों प्रमाण मानते हैं — यह दुर्लभ सहमति है।'],
['m63','adults','scripture',0,'The Jain Agamas were written down immediately after Mahavira’s nirvana.','जैन आगम महावीर के निर्वाण के तुरंत बाद लिख लिए गए थे।','They were carried orally for many centuries before being committed to writing, which is part of why traditions differ today.','वे अनेक शताब्दियों तक मौखिक परंपरा में रहे, उसके पश्चात लिखे गए — आज परंपराओं में भेद का एक कारण यही है।'],
['m64','kids','scripture',1,'Jain holy books are treated with great respect.','जैन ग्रंथों का अति आदर किया जाता है।','Yes. Scriptures are not placed on the floor, are handled with clean hands, and are honoured on Shrut Panchami.','जी। ग्रंथों को भूमि पर नहीं रखा जाता, शुद्ध हाथों से छुआ जाता है, और श्रुत पंचमी पर उनका सम्मान किया जाता है।'],
['m65','adults','scripture',1,'The Samayasara teaches that the soul alone is the agent of its own karma.','समयसार का उपदेश है कि आत्मा ही अपने कर्मों की कर्ता है।','Correct. Kundakunda insists that the soul, not the body or the world, binds and sheds karma — and so the soul alone can free itself.','सही। कुन्दकुन्द कहते हैं कि कर्म का बंध और निर्जरा शरीर या लोक नहीं, आत्मा स्वयं करती है — अतः मुक्ति भी आत्मा ही साध सकती है।'],
['m66','both','scripture',0,'Jain scriptures teach that ritual alone brings liberation.','जैन ग्रंथ कहते हैं कि केवल कर्मकांड से मोक्ष मिलता है।','Ritual without right faith, knowledge and conduct is empty. The texts insist that inner transformation is what liberates.','सम्यक् दर्शन, ज्ञान और चारित्र के बिना कर्मकांड निष्फल है। ग्रंथ कहते हैं कि मुक्ति भीतर का परिवर्तन ही दिलाता है।'],
['m67','adults','scripture',1,'Umasvati is also known as Umasvami.','उमास्वाति को उमास्वामी भी कहा जाता है।','Correct. Both forms of the name are used for the author of the Tattvartha Sutra.','सही। तत्त्वार्थसूत्र के रचयिता हेतु दोनों रूप प्रचलित हैं।'],
['m68','both','digambar',0,'Digambara means white-clad.','दिगंबर का अर्थ है श्वेत वस्त्रधारी।','Digambara means sky-clad — clothed in the directions alone, owning nothing. Shvetambara is the tradition that means white-clad.','दिगंबर का अर्थ है आकाश-वस्त्र — केवल दिशाओं को ही वस्त्र मानने वाले, जो कुछ भी परिग्रह नहीं रखते। श्वेत वस्त्रधारी को श्वेतांबर कहते हैं।'],
['m69','both','digambar',1,'Digambar tradition holds that Mahavira never married.','दिगंबर परंपरा मानती है कि महावीर ने विवाह नहीं किया।','Correct. The Digambar tradition records him as unmarried, while other traditions differ on this point.','सही। दिगंबर परंपरा में उन्हें अविवाहित बताया जाता है, जबकि अन्य परंपराएँ इस विषय में भिन्न मत रखती हैं।'],
['m70','adults','digambar',0,'Digambar and Shvetambara disagree on every doctrine.','दिगंबर और श्वेतांबर हर सिद्धांत पर असहमत हैं।','They agree on the essentials — the Tirthankaras, karma, the three jewels and the five great vows. Their differences are chiefly monastic practice and a few details.','मूल बातों पर दोनों सहमत हैं — तीर्थंकर, कर्म, रत्नत्रय और पाँच महाव्रत। भेद मुख्यतः मुनि-आचार और कुछ विवरणों में है।'],
['m71','kids','digambar',1,'Digambar temples often have very simple, calm images.','दिगंबर मंदिरों की मूर्तियाँ प्रायः अति सरल और शांत होती हैं।','Yes. The images are unadorned and face serene, reflecting a soul wholly free of attachment.','जी। मूर्तियाँ अलंकृत नहीं होतीं और मुख शांत होता है — यह सब आसक्ति से पूर्णतः मुक्त आत्मा का बोध कराता है।'],
['m72','adults','digambar',1,'Digambar tradition reveres the Samavasarana as a universal assembly.','दिगंबर परंपरा समवसरण को सार्वभौम सभा के रूप में आदरती है।','Correct. It is the divine assembly where a Tirthankara’s teaching reaches every being in its own language, without exclusion.','सही। यह वह दिव्य सभा है जहाँ तीर्थंकर का उपदेश हर जीव तक उसकी अपनी भाषा में पहुँचता है, किसी को बाहर रखे बिना।']
];
