/* ============================================================
   UI DICTIONARY · every visible string lives here
   ============================================================ */
var UI = {
  en: {
    brandHi: 'मिथक भंजन', brandEn: 'Myth Busters',
    langSwitch: 'हिंदी', hub: 'All games', restart: 'Restart',
    soundOn: 'Sound on', soundOff: 'Sound off',
    s1Title: 'Choose your language', s1Sub: 'अपनी भाषा चुनिए',
    s2Title: 'Who is playing?',
    s2Sub: 'The children’s round keeps to everyday questions. The adults’ round goes deeper into doctrine, scripture and tradition.',
    kids: 'Kids', kidsNote: 'Baalak · everyday questions',
    adults: 'Adults', adultsNote: 'Vyask · doctrine and scripture',
    s3Title: 'Set up your round',
    s3Sub: 'Choose how many statements you want, and how much time each one gets.',
    nameLabel: 'Your name (kept on this device only)', namePh: 'e.g. Vraddhim',
    roundLabel: 'How many statements?', roundAll: 'All of them',
    timerLabel: 'Time per statement',
    timer: { relaxed: 'Relaxed · 20s', standard: 'Standard · 12s', quick: 'Quick · 8s', none: 'No timer' },
    start: 'Begin', leaderboard: 'Leaderboard',
    setupHint: 'Press T for true and F for false, or tap a button. When you are wrong, a short lesson follows.',
    nameNeeded: 'Please write your name first.',
    hudScore: 'Points', hudStreak: 'Streak', hudAcc: 'Accuracy', hudNum: 'Statement',
    btnTrue: 'TRUE', btnFalse: 'FALSE',
    correctTitle: 'Correct!', wrongTitle: 'Not quite.', timeoutTitle: 'Time is up.',
    mythStamp: 'MYTH BUSTED',
    trueLead: 'True — ', falseLead: 'It is false — ',
    points: '+{n} points',
    next: 'Next statement →',
    quit: 'Leave this round',
    quitConfirm: 'Leave this round?', quitBody: 'Your progress in this round will be lost.',
    yes: 'Yes, leave', no: 'Keep playing',
    resTitle: ['Curious beginner', 'Solid seeker', 'Myth-busting master', 'Tirthankara-level'],
    resSub: ['Every journey starts with one step. You learned something new today.',
             'Good effort. Revisit the myths that caught you and try again.',
             'Excellent. Your knowledge shines like a diya on Diwali.',
             'Perfect. You truly understand the Jain path. Micchami Dukkadam.'],
    statScore: 'Points', statAcc: 'Accuracy', statCorrect: 'Correct', statBest: 'Best streak',
    rankLine: 'You are #{n} on this device',
    cheers: ['Sadhu! Sadhu! A clear mind sees the truth.',
             'Well done — knowledge is the lamp that guides conduct.',
             'Sadhu! Every myth you released makes room for understanding.',
             'Beautiful. Right knowledge is one of the three jewels.',
             'Sadhu! Sadhu! You answered with a steady mind.'],
    again: 'Play again', changeSetup: 'Change set-up', showLb: 'Leaderboard',
    reviewTitle: 'The statements that caught you',
    reviewEmpty: 'Nothing was missed — here are four worth remembering.',
    lbTitle: 'Leaderboard · highest scores', lbClear: 'Clear',
    lbEmpty: 'No records yet. Be the first!',
    lbConfirmTitle: 'Clear the leaderboard?',
    lbConfirmBody: 'Every record for this game will be removed from this device.',
    lbCleared: 'Records cleared.',
    thRank: '#', thLbName: 'Name', thLbLevel: 'Level', thLbTime: 'Time', thLbScore: 'Points',
    storageOff: 'Records cannot be saved in a private window — the game still plays.',
    saved: 'Round saved · {n} points',
    foot: 'Rooted in the Digambar Jain tradition. Understanding varies by family and lineage — always ask your elders.'
  },
  hi: {
    brandHi: 'मिथक भंजन', brandEn: 'Myth Busters',
    langSwitch: 'English', hub: 'सभी खेल', restart: 'पुनः आरंभ',
    soundOn: 'ध्वनि चालू', soundOff: 'ध्वनि बंद',
    s1Title: 'अपनी भाषा चुनिए', s1Sub: 'Choose your language',
    s2Title: 'कौन खेल रहा है?',
    s2Sub: 'बालकों की बारी में रोज़मर्रा के प्रश्न हैं। व्यस्कों की बारी में सिद्धांत, ग्रंथ और परंपरा की गहराई है।',
    kids: 'बालक', kidsNote: 'रोज़मर्रा के प्रश्न',
    adults: 'व्यस्क', adultsNote: 'सिद्धांत और ग्रंथ',
    s3Title: 'अपनी बारी सजाइए',
    s3Sub: 'तय कीजिए कि कितने कथन लेने हैं और प्रत्येक को कितना समय मिले।',
    nameLabel: 'आपका नाम (केवल इसी उपकरण में संचित)', namePh: 'जैसे वृद्धिम',
    roundLabel: 'कितने कथन?', roundAll: 'सभी',
    timerLabel: 'प्रति कथन समय',
    timer: { relaxed: 'विश्राम · 20 से', standard: 'सामान्य · 12 से', quick: 'शीघ्र · 8 से', none: 'कोई समय-सीमा नहीं' },
    start: 'आरंभ कीजिए', leaderboard: 'उपलब्धि सूची',
    setupHint: 'सत्य हेतु T और मिथ्या हेतु F दबाइए, या बटन छूइए। उत्तर भूल होने पर एक छोटा पाठ दिखाया जाता है।',
    nameNeeded: 'कृपया पहले अपना नाम लिखिए।',
    hudScore: 'अंक', hudStreak: 'क्रम', hudAcc: 'सटीकता', hudNum: 'कथन',
    btnTrue: 'सत्य', btnFalse: 'मिथ्या',
    correctTitle: 'बिल्कुल सही!', wrongTitle: 'ठीक नहीं।', timeoutTitle: 'समय समाप्त।',
    mythStamp: 'मिथक भंजन',
    trueLead: 'सत्य है — ', falseLead: 'यह मिथ्या है — ',
    points: '+{n} अंक',
    next: 'अगला कथन →',
    quit: 'यह बारी छोड़िए',
    quitConfirm: 'यह बारी छोड़ें?', quitBody: 'इस बारी की प्रगति मिट जाएगी।',
    yes: 'हाँ, छोड़ दीजिए', no: 'खेलते रहिए',
    resTitle: ['जिज्ञासु आरंभ', 'दृढ़ साधक', 'मिथक-भंजक निपुण', 'तीर्थंकर-कोटि'],
    resSub: ['हर यात्रा एक कदम से आरंभ होती है। आज आपने कुछ नया सीखा।',
             'अच्छा प्रयास। जिन मिथकों ने पकड़ा उन्हें पुनः पढ़िए और फिर खेलिए।',
             'उत्कृष्ट। आपका ज्ञान दीपावली के दीप जैसा प्रकाशमान है।',
             'पूर्ण। आप जैन पथ को सचमुच समझते हैं। मिच्छामि दुक्कड़म्।'],
    statScore: 'अंक', statAcc: 'सटीकता', statCorrect: 'सही', statBest: 'श्रेष्ठ क्रम',
    rankLine: 'इस उपकरण पर आप #{n} स्थान पर हैं',
    cheers: ['साधु! साधु! निर्मल मन ही सत्य देख पाता है।',
             'बहुत सुंदर — ज्ञान ही वह दीप है जो आचरण को दिशा देता है।',
             'साधु! हर मिथक का त्याग समझ के लिए स्थान बनाता है।',
             'अद्भुत। सम्यक् ज्ञान भी तीन रत्नों में से एक है।',
             'साधु! साधु! आपने स्थिर मन से उत्तर दिया।'],
    again: 'पुनः खेलिए', changeSetup: 'सेटिंग बदलिए', showLb: 'उपलब्धि सूची',
    reviewTitle: 'जिन कथनों ने पकड़ा',
    reviewEmpty: 'कोई भूल नहीं हुई — ये चार याद रखने योग्य हैं।',
    lbTitle: 'उपलब्धि सूची · सर्वाधिक अंक', lbClear: 'हटाइए',
    lbEmpty: 'अभी कोई रिकॉर्ड नहीं। पहले खिलाड़ी बनिए!',
    lbConfirmTitle: 'उपलब्धि सूची हटाएँ?',
    lbConfirmBody: 'इस खेल के सभी रिकॉर्ड इस उपकरण से हट जाएँगे।',
    lbCleared: 'रिकॉर्ड हटा दिए गए।',
    thRank: '#', thLbName: 'नाम', thLbLevel: 'स्तर', thLbTime: 'समय', thLbScore: 'अंक',
    storageOff: 'निजी विंडो में रिकॉर्ड संचित नहीं हो सकते — खेल सामान्य रूप से चलता रहेगा।',
    saved: 'बारी संचित हुई · {n} अंक',
    foot: 'दिगंबर जैन परंपरा से प्रेरित। समझ परिवार और परंपरा अनुसार भिन्न हो सकती है — अपने बड़ों से अवश्य पूछिए।'
  }
};

